// Lessons — each pairs a small vocab set with ONE grammar point, then drills
// sentences that recombine those words as much as naturally possible.
// Lessons are grouped into sections (ordered = increasing difficulty).
//
// Shape:
//   { id, section, title, grammar, grammarNote,
//     vocab: [{jp, romaji, en, pos}],
//     sentences: [{ en, jp, romaji, hint?, words:[{jp,en,pos}] }] }
//
// pos (color coding): n=noun v=verb adj=adjective adv=adverb
//                     prt=particle cop=copula expr=expression
//                     aux=auxiliary conj=conjunction

window.SECTIONS = [
  "Level 1 · First contact",
  "Level 2 · Getting things",
  "Level 3 · Time & when",
  "Level 4 · Daily life",
  "Level 5 · The past",
  "Level 6 · Wants & plans",
  "Level 7 · Describing things",
  "Level 8 · Feelings & opinions",
  "Level 9 · Connecting ideas",
  "Level 10 · Out in the world",
];

window.LESSONS = [
  // ============================================================
  // BASICS
  // ============================================================
  {
    id: "intro",
    section: "Level 1 · First contact",
    title: "Hello & introductions",
    grammar: "X は Y です  ·  か",
    grammarNote:
      "は marks the topic (what you're talking about); です means is/am. Add か at the very end to turn a statement into a question.",
    vocab: [
      { jp: "わたし", romaji: "watashi", en: "I / me", pos: "n" },
      { jp: "がくせい", romaji: "gakusei", en: "student", pos: "n" },
      { jp: "アメリカじん", romaji: "amerika-jin", en: "American", pos: "n" },
      { jp: "ともだち", romaji: "tomodachi", en: "friend", pos: "n" },
      { jp: "なまえ", romaji: "namae", en: "name  (お = polite)", pos: "n" },
      { jp: "なん", romaji: "nan", en: "what", pos: "n" },
    ],
    sentences: [
      { en: "Nice to meet you.", jp: "はじめまして。", romaji: "hajimemashite.",
        words: [{jp:"はじめまして",en:"nice to meet you",pos:"expr"}] },
      { en: "I'm Tom.", jp: "わたしは トムです。", romaji: "watashi wa Tomu desu.", hint: "は marks the topic",
        words: [{jp:"わたし",en:"I",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"トム",en:"Tom",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
      { en: "I'm American.", jp: "わたしは アメリカじんです。", romaji: "watashi wa amerika-jin desu.",
        words: [{jp:"わたし",en:"I",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"アメリカじん",en:"American",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
      { en: "I'm a student.", jp: "わたしは がくせいです。", romaji: "watashi wa gakusei desu.",
        words: [{jp:"わたし",en:"I",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"がくせい",en:"student",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
      { en: "My friend is a student.", jp: "ともだちは がくせいです。", romaji: "tomodachi wa gakusei desu.",
        words: [{jp:"ともだち",en:"friend",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"がくせい",en:"student",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "What's your name?", jp: "おなまえは なんですか？", romaji: "onamae wa nan desu ka?", hint: "か makes it a question",
        words: [{jp:"おなまえ",en:"(your) name",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"なん",en:"what",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
    ],
  },
  {
    id: "greetings",
    section: "Level 1 · First contact",
    title: "Greetings & courtesies",
    grammar: "あいさつ — set phrases",
    grammarNote:
      "These greetings never change form — learn each as one chunk. ございます makes おはよう and ありがとう more polite.",
    vocab: [
      { jp: "おはよう", romaji: "ohayou", en: "good morning", pos: "expr" },
      { jp: "こんにちは", romaji: "konnichiwa", en: "hello / good afternoon", pos: "expr" },
      { jp: "こんばんは", romaji: "konbanwa", en: "good evening", pos: "expr" },
      { jp: "ありがとう", romaji: "arigatou", en: "thank you", pos: "expr" },
      { jp: "すみません", romaji: "sumimasen", en: "excuse me / sorry", pos: "expr" },
      { jp: "さようなら", romaji: "sayounara", en: "goodbye", pos: "expr" },
      { jp: "はい", romaji: "hai", en: "yes", pos: "expr" },
      { jp: "いいえ", romaji: "iie", en: "no", pos: "expr" },
    ],
    sentences: [
      { en: "Good morning.", jp: "おはよう ございます。", romaji: "ohayou gozaimasu.", hint: "ございます = polite",
        words: [{jp:"おはよう",en:"good morning",pos:"expr"},{jp:"ございます",en:"[polite]",pos:"aux"}] },
      { en: "Hello.", jp: "こんにちは。", romaji: "konnichiwa.",
        words: [{jp:"こんにちは",en:"hello",pos:"expr"}] },
      { en: "Good evening.", jp: "こんばんは。", romaji: "konbanwa.",
        words: [{jp:"こんばんは",en:"good evening",pos:"expr"}] },
      { en: "Thank you very much.", jp: "ありがとう ございます。", romaji: "arigatou gozaimasu.",
        words: [{jp:"ありがとう",en:"thank you",pos:"expr"},{jp:"ございます",en:"[polite]",pos:"aux"}] },
      { en: "Excuse me. / I'm sorry.", jp: "すみません。", romaji: "sumimasen.",
        words: [{jp:"すみません",en:"excuse me / sorry",pos:"expr"}] },
      { en: "Yes, that's right.", jp: "はい、そうです。", romaji: "hai, sou desu.", hint: "そう = so / that way",
        words: [{jp:"はい",en:"yes",pos:"expr"},{jp:"そう",en:"that way",pos:"adv"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "No, that's wrong.", jp: "いいえ、ちがいます。", romaji: "iie, chigaimasu.",
        words: [{jp:"いいえ",en:"no",pos:"expr"},{jp:"ちがいます",en:"is wrong / differs",pos:"v"}] },
      { en: "Goodbye.", jp: "さようなら。", romaji: "sayounara.",
        words: [{jp:"さようなら",en:"goodbye",pos:"expr"}] },
    ],
  },
  {
    id: "this-that",
    section: "Level 1 · First contact",
    title: "This, that & “whose”",
    grammar: "これ・それ・あれ  ·  の",
    grammarNote:
      "これ = this (by me), それ = that (by you), あれ = that (over there), どれ = which. の links two nouns: わたしの ほん = my book.",
    vocab: [
      { jp: "これ", romaji: "kore", en: "this", pos: "n" },
      { jp: "それ", romaji: "sore", en: "that (by you)", pos: "n" },
      { jp: "あれ", romaji: "are", en: "that (over there)", pos: "n" },
      { jp: "どれ", romaji: "dore", en: "which one", pos: "n" },
      { jp: "ほん", romaji: "hon", en: "book", pos: "n" },
      { jp: "かばん", romaji: "kaban", en: "bag", pos: "n" },
      { jp: "わたしの", romaji: "watashi no", en: "my / mine", pos: "n" },
    ],
    sentences: [
      { en: "What is this?", jp: "これは なんですか？", romaji: "kore wa nan desu ka?",
        words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"なん",en:"what",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "This is a book.", jp: "これは ほんです。", romaji: "kore wa hon desu.",
        words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ほん",en:"book",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "That (by you) is a bag.", jp: "それは かばんです。", romaji: "sore wa kaban desu.",
        words: [{jp:"それ",en:"that",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"かばん",en:"bag",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "That over there is my bag.", jp: "あれは わたしの かばんです。", romaji: "are wa watashi no kaban desu.", hint: "の = 's / of",
        words: [{jp:"あれ",en:"that over there",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"わたし",en:"I",pos:"n"},{jp:"の",en:"'s",pos:"prt"},{jp:"かばん",en:"bag",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "This is my book.", jp: "これは わたしの ほんです。", romaji: "kore wa watashi no hon desu.",
        words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"わたし",en:"I",pos:"n"},{jp:"の",en:"'s",pos:"prt"},{jp:"ほん",en:"book",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "Which one is your book?", jp: "どれが あなたの ほんですか？", romaji: "dore ga anata no hon desu ka?", hint: "あなた = you",
        words: [{jp:"どれ",en:"which one",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"あなた",en:"you",pos:"n"},{jp:"の",en:"'s",pos:"prt"},{jp:"ほん",en:"book",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Is that (by you) a book?", jp: "それは ほんですか？", romaji: "sore wa hon desu ka?",
        words: [{jp:"それ",en:"that",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ほん",en:"book",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
    ],
  },
  {
    id: "numbers",
    section: "Level 1 · First contact",
    title: "Numbers 1–10 & age",
    grammar: "すうじ 1–10  ·  なんさいですか",
    grammarNote:
      "The core numbers 1–10 — they power prices, time and counting later. To ask age: なんさいですか. Note 20 years old is the irregular はたち.",
    vocab: [
      { jp: "いち", romaji: "ichi", en: "one (1)", pos: "n" },
      { jp: "に", romaji: "ni", en: "two (2)", pos: "n" },
      { jp: "さん", romaji: "san", en: "three (3)", pos: "n" },
      { jp: "よん", romaji: "yon", en: "four (4)", pos: "n" },
      { jp: "ご", romaji: "go", en: "five (5)", pos: "n" },
      { jp: "ろく", romaji: "roku", en: "six (6)", pos: "n" },
      { jp: "なな", romaji: "nana", en: "seven (7)", pos: "n" },
      { jp: "はち", romaji: "hachi", en: "eight (8)", pos: "n" },
      { jp: "きゅう", romaji: "kyuu", en: "nine (9)", pos: "n" },
      { jp: "じゅう", romaji: "juu", en: "ten (10)", pos: "n" },
      { jp: "なんさい", romaji: "nan-sai", en: "how old", pos: "n" },
      { jp: "はたち", romaji: "hatachi", en: "20 years old", pos: "n" },
    ],
    sentences: [
      { en: "One, two, three, four, five.", jp: "いち、に、さん、よん、ご。", romaji: "ichi, ni, san, yon, go.",
        words: [{jp:"いち",en:"1",pos:"n"},{jp:"に",en:"2",pos:"n"},{jp:"さん",en:"3",pos:"n"},{jp:"よん",en:"4",pos:"n"},{jp:"ご",en:"5",pos:"n"}] },
      { en: "Six, seven, eight, nine, ten.", jp: "ろく、なな、はち、きゅう、じゅう。", romaji: "roku, nana, hachi, kyuu, juu.",
        words: [{jp:"ろく",en:"6",pos:"n"},{jp:"なな",en:"7",pos:"n"},{jp:"はち",en:"8",pos:"n"},{jp:"きゅう",en:"9",pos:"n"},{jp:"じゅう",en:"10",pos:"n"}] },
      { en: "How old are you?", jp: "なんさいですか？", romaji: "nan-sai desu ka?",
        words: [{jp:"なんさい",en:"how old",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "I'm twenty years old.", jp: "はたちです。", romaji: "hatachi desu.", hint: "20 = はたち (irregular)",
        words: [{jp:"はたち",en:"20 years old",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
      { en: "My friend is nine years old.", jp: "ともだちは きゅうさいです。", romaji: "tomodachi wa kyuu-sai desu.", hint: "〜さい = years old",
        words: [{jp:"ともだち",en:"friend",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"きゅう",en:"9",pos:"n"},{jp:"さい",en:"years old",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "How old is your friend?", jp: "ともだちは なんさいですか？", romaji: "tomodachi wa nan-sai desu ka?",
        words: [{jp:"ともだち",en:"friend",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"なんさい",en:"how old",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
    ],
  },
  {
    id: "shop",
    section: "Level 2 · Getting things",
    title: "At a shop — ordering & prices",
    grammar: "〜を ください  ·  〜は いくらですか",
    grammarNote:
      "を marks the thing you want; add ください to politely ask for it. To ask a price: [thing] は いくらですか？",
    vocab: [
      { jp: "これ", romaji: "kore", en: "this", pos: "n" },
      { jp: "いくら", romaji: "ikura", en: "how much", pos: "n" },
      { jp: "みず", romaji: "mizu", en: "water", pos: "n" },
      { jp: "コーヒー", romaji: "koohii", en: "coffee", pos: "n" },
      { jp: "ひとつ", romaji: "hitotsu", en: "one (item)", pos: "n" },
      { jp: "ください", romaji: "kudasai", en: "please give me", pos: "aux" },
    ],
    sentences: [
      { en: "How much is this?", jp: "これは いくらですか？", romaji: "kore wa ikura desu ka?",
        words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いくら",en:"how much",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Water, please.", jp: "みずを ください。", romaji: "mizu o kudasai.", hint: "を marks what you want",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "Coffee, please.", jp: "コーヒーを ください。", romaji: "koohii o kudasai.",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "One coffee, please.", jp: "コーヒーを ひとつ ください。", romaji: "koohii o hitotsu kudasai.",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ひとつ",en:"one",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "This one, please.", jp: "これを ください。", romaji: "kore o kudasai.",
        words: [{jp:"これ",en:"this",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "How much is the water?", jp: "みずは いくらですか？", romaji: "mizu wa ikura desu ka?",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いくら",en:"how much",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
    ],
  },
  {
    id: "money",
    section: "Level 2 · Getting things",
    title: "Money & prices",
    grammar: "ひゃく・せん  ·  〜えん  ·  いくら",
    grammarNote:
      "Bigger numbers: ひゃく = 100, せん = 1000. Prices take 〜えん (yen). Watch the sound-shift: 300 is さんびゃく, not さんひゃく.",
    vocab: [
      { jp: "ひゃく", romaji: "hyaku", en: "hundred (100)", pos: "n" },
      { jp: "せん", romaji: "sen", en: "thousand (1000)", pos: "n" },
      { jp: "えん", romaji: "en", en: "yen (¥)", pos: "n" },
      { jp: "ごひゃく", romaji: "gohyaku", en: "500", pos: "n" },
      { jp: "いくら", romaji: "ikura", en: "how much", pos: "n" },
      { jp: "たかい", romaji: "takai", en: "expensive", pos: "adj" },
      { jp: "やすい", romaji: "yasui", en: "cheap", pos: "adj" },
    ],
    sentences: [
      { en: "How much is this?", jp: "これは いくらですか？", romaji: "kore wa ikura desu ka?",
        words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いくら",en:"how much",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "It's 100 yen.", jp: "ひゃくえんです。", romaji: "hyaku-en desu.",
        words: [{jp:"ひゃく",en:"100",pos:"n"},{jp:"えん",en:"yen",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "It's 500 yen.", jp: "ごひゃくえんです。", romaji: "gohyaku-en desu.",
        words: [{jp:"ごひゃく",en:"500",pos:"n"},{jp:"えん",en:"yen",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "The coffee is 300 yen.", jp: "コーヒーは さんびゃくえんです。", romaji: "koohii wa sanbyaku-en desu.", hint: "300 = さんびゃく (sound shift)",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"さんびゃく",en:"300",pos:"n"},{jp:"えん",en:"yen",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "Is it expensive?", jp: "たかいですか？", romaji: "takai desu ka?",
        words: [{jp:"たかい",en:"expensive",pos:"adj"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "No, it's cheap.", jp: "いいえ、やすいです。", romaji: "iie, yasui desu.",
        words: [{jp:"いいえ",en:"no",pos:"expr"},{jp:"やすい",en:"cheap",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "The water is 100 yen.", jp: "みずは ひゃくえんです。", romaji: "mizu wa hyaku-en desu.",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ひゃく",en:"100",pos:"n"},{jp:"えん",en:"yen",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
    ],
  },
  {
    id: "counters",
    section: "Level 2 · Getting things",
    title: "Counting things (ひとつ…)",
    grammar: "ひとつ〜とお  ·  〜を [かず] ください",
    grammarNote:
      "The all-purpose counter: ひとつ(1), ふたつ(2), みっつ(3), よっつ(4), いつつ(5)… up to とお(10). Order things with [thing]を [number] ください.",
    vocab: [
      { jp: "ひとつ", romaji: "hitotsu", en: "one (item)", pos: "n" },
      { jp: "ふたつ", romaji: "futatsu", en: "two (items)", pos: "n" },
      { jp: "みっつ", romaji: "mittsu", en: "three (items)", pos: "n" },
      { jp: "よっつ", romaji: "yottsu", en: "four (items)", pos: "n" },
      { jp: "いつつ", romaji: "itsutsu", en: "five (items)", pos: "n" },
      { jp: "いくつ", romaji: "ikutsu", en: "how many", pos: "n" },
      { jp: "ぜんぶ", romaji: "zenbu", en: "all of it", pos: "n" },
    ],
    sentences: [
      { en: "One, please.", jp: "ひとつ ください。", romaji: "hitotsu kudasai.",
        words: [{jp:"ひとつ",en:"one",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "Two coffees, please.", jp: "コーヒーを ふたつ ください。", romaji: "koohii o futatsu kudasai.",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ふたつ",en:"two",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "Three waters, please.", jp: "みずを みっつ ください。", romaji: "mizu o mittsu kudasai.",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みっつ",en:"three",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "How many?", jp: "いくつですか？", romaji: "ikutsu desu ka?", hint: "いくつ = how many",
        words: [{jp:"いくつ",en:"how many",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Five, please.", jp: "いつつ ください。", romaji: "itsutsu kudasai.",
        words: [{jp:"いつつ",en:"five",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "All of it, please.", jp: "ぜんぶ ください。", romaji: "zenbu kudasai.",
        words: [{jp:"ぜんぶ",en:"all",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
    ],
  },
  {
    id: "where",
    section: "Level 2 · Getting things",
    title: "Where is it? (ここ・どこ)",
    grammar: "ここ・そこ・あそこ・どこ  ·  〜に あります／います",
    grammarNote:
      "ここ=here, そこ=there (by you), あそこ=over there, どこ=where. あります = there is (things); います = there is (people/animals). The place takes に.",
    vocab: [
      { jp: "ここ", romaji: "koko", en: "here", pos: "n" },
      { jp: "そこ", romaji: "soko", en: "there (by you)", pos: "n" },
      { jp: "あそこ", romaji: "asoko", en: "over there", pos: "n" },
      { jp: "どこ", romaji: "doko", en: "where", pos: "n" },
      { jp: "トイレ", romaji: "toire", en: "toilet / restroom", pos: "n" },
      { jp: "えき", romaji: "eki", en: "station", pos: "n" },
      { jp: "あります", romaji: "arimasu", en: "there is (a thing)", pos: "v" },
      { jp: "います", romaji: "imasu", en: "there is (a person)", pos: "v" },
    ],
    sentences: [
      { en: "Where is the restroom?", jp: "トイレは どこですか？", romaji: "toire wa doko desu ka?", hint: "the most useful sentence!",
        words: [{jp:"トイレ",en:"restroom",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"どこ",en:"where",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "It's over there.", jp: "あそこです。", romaji: "asoko desu.",
        words: [{jp:"あそこ",en:"over there",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "The station is here.", jp: "えきは ここです。", romaji: "eki wa koko desu.",
        words: [{jp:"えき",en:"station",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ここ",en:"here",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "Is there (any) water?", jp: "みずは ありますか？", romaji: "mizu wa arimasu ka?",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"あります",en:"there is",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Yes, it's here.", jp: "はい、ここに あります。", romaji: "hai, koko ni arimasu.", hint: "に marks the place",
        words: [{jp:"はい",en:"yes",pos:"expr"},{jp:"ここ",en:"here",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"あります",en:"there is",pos:"v"}] },
      { en: "My friend is over there.", jp: "ともだちは あそこに います。", romaji: "tomodachi wa asoko ni imasu.", hint: "います for people",
        words: [{jp:"ともだち",en:"friend",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"あそこ",en:"over there",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"います",en:"there is",pos:"v"}] },
      { en: "Where is the station?", jp: "えきは どこですか？", romaji: "eki wa doko desu ka?",
        words: [{jp:"えき",en:"station",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"どこ",en:"where",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
    ],
  },
  {
    id: "cafe",
    section: "Level 2 · Getting things",
    title: "At the café (putting it together)",
    grammar: "review  ·  〜と〜  ·  おねがいします",
    grammarNote:
      "Combine ordering, counting and prices. と joins nouns (A と B = A and B); おねがいします is a polite “please” for requests.",
    vocab: [
      { jp: "おちゃ", romaji: "ocha", en: "(green) tea", pos: "n" },
      { jp: "ケーキ", romaji: "keeki", en: "cake", pos: "n" },
      { jp: "メニュー", romaji: "menyuu", en: "menu", pos: "n" },
      { jp: "おねがいします", romaji: "onegai-shimasu", en: "please (request)", pos: "expr" },
      { jp: "コーヒー", romaji: "koohii", en: "coffee", pos: "n" },
      { jp: "みず", romaji: "mizu", en: "water", pos: "n" },
    ],
    sentences: [
      { en: "The menu, please.", jp: "メニューを おねがいします。", romaji: "menyuu o onegai-shimasu.", hint: "おねがいします = polite please",
        words: [{jp:"メニュー",en:"menu",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"おねがいします",en:"please",pos:"expr"}] },
      { en: "A coffee and a tea, please.", jp: "コーヒーと おちゃを ください。", romaji: "koohii to ocha o kudasai.", hint: "と = and",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"と",en:"and",pos:"prt"},{jp:"おちゃ",en:"tea",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "How much is the cake?", jp: "ケーキは いくらですか？", romaji: "keeki wa ikura desu ka?",
        words: [{jp:"ケーキ",en:"cake",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いくら",en:"how much",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Two teas, please.", jp: "おちゃを ふたつ ください。", romaji: "ocha o futatsu kudasai.",
        words: [{jp:"おちゃ",en:"tea",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ふたつ",en:"two",pos:"n"},{jp:"ください",en:"please give me",pos:"aux"}] },
      { en: "Water, please.", jp: "みずを おねがいします。", romaji: "mizu o onegai-shimasu.",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"おねがいします",en:"please",pos:"expr"}] },
      { en: "Thank you very much.", jp: "ありがとう ございます。", romaji: "arigatou gozaimasu.",
        words: [{jp:"ありがとう",en:"thank you",pos:"expr"},{jp:"ございます",en:"[polite]",pos:"aux"}] },
    ],
  },
  {
    id: "verbs",
    section: "Level 3 · Doing things",
    title: "Doing things (〜ます)",
    grammar: "polite present 〜ます",
    grammarNote:
      "〜ます is the polite present — it covers what you do, habits, and the near future (“I do / I'll do”). Each verb has its own ます-form; learn these core ones first.",
    vocab: [
      { jp: "たべます", romaji: "tabemasu", en: "eat  (食べる)", pos: "v" },
      { jp: "のみます", romaji: "nomimasu", en: "drink  (飲む)", pos: "v" },
      { jp: "みます", romaji: "mimasu", en: "see / watch  (見る)", pos: "v" },
      { jp: "いきます", romaji: "ikimasu", en: "go  (行く)", pos: "v" },
      { jp: "します", romaji: "shimasu", en: "do  (する)", pos: "v" },
      { jp: "わかります", romaji: "wakarimasu", en: "understand  (分かる)", pos: "v" },
    ],
    sentences: [
      { en: "I'll eat.", jp: "たべます。", romaji: "tabemasu.",
        words: [{jp:"たべ",en:"eat",pos:"v"},{jp:"ます",en:"[polite]",pos:"aux"}] },
      { en: "I'll drink.", jp: "のみます。", romaji: "nomimasu.",
        words: [{jp:"のみ",en:"drink",pos:"v"},{jp:"ます",en:"[polite]",pos:"aux"}] },
      { en: "I'll watch.", jp: "みます。", romaji: "mimasu.",
        words: [{jp:"み",en:"watch",pos:"v"},{jp:"ます",en:"[polite]",pos:"aux"}] },
      { en: "I'm going.", jp: "いきます。", romaji: "ikimasu.",
        words: [{jp:"いき",en:"go",pos:"v"},{jp:"ます",en:"[polite]",pos:"aux"}] },
      { en: "I'll do it.", jp: "します。", romaji: "shimasu.",
        words: [{jp:"し",en:"do",pos:"v"},{jp:"ます",en:"[polite]",pos:"aux"}] },
      { en: "I understand.", jp: "わかります。", romaji: "wakarimasu.", hint: "also: “I get it”",
        words: [{jp:"わかり",en:"understand",pos:"v"},{jp:"ます",en:"[polite]",pos:"aux"}] },
    ],
  },
  {
    id: "object",
    section: "Level 3 · Doing things",
    title: "What you do it to (を)",
    grammar: "〜を 〜ます  (object + verb)",
    grammarNote:
      "を marks the direct object — the thing the verb acts on: [thing]を [verb]ます. The object comes before the verb.",
    vocab: [
      { jp: "ごはん", romaji: "gohan", en: "rice / meal", pos: "n" },
      { jp: "ほん", romaji: "hon", en: "book", pos: "n" },
      { jp: "えいが", romaji: "eiga", en: "movie", pos: "n" },
      { jp: "にほんご", romaji: "nihongo", en: "Japanese (language)", pos: "n" },
      { jp: "よみます", romaji: "yomimasu", en: "read  (読む)", pos: "v" },
      { jp: "みず", romaji: "mizu", en: "water", pos: "n" },
    ],
    sentences: [
      { en: "I eat a meal.", jp: "ごはんを たべます。", romaji: "gohan o tabemasu.",
        words: [{jp:"ごはん",en:"meal",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべます",en:"eat",pos:"v"}] },
      { en: "I drink water.", jp: "みずを のみます。", romaji: "mizu o nomimasu.",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
      { en: "I watch a movie.", jp: "えいがを みます。", romaji: "eiga o mimasu.",
        words: [{jp:"えいが",en:"movie",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みます",en:"watch",pos:"v"}] },
      { en: "I read a book.", jp: "ほんを よみます。", romaji: "hon o yomimasu.",
        words: [{jp:"ほん",en:"book",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"よみます",en:"read",pos:"v"}] },
      { en: "I read Japanese.", jp: "にほんごを よみます。", romaji: "nihongo o yomimasu.",
        words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"よみます",en:"read",pos:"v"}] },
      { en: "I drink coffee.", jp: "コーヒーを のみます。", romaji: "koohii o nomimasu.",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
    ],
  },
  {
    id: "negative",
    section: "Level 3 · Doing things",
    title: "Saying no & asking (〜ません／〜ますか)",
    grammar: "〜ません (don't)  ·  〜ますか (do you…?)",
    grammarNote:
      "Make a verb negative by swapping ます for ません. Turn any statement into a yes/no question by adding か on the end: 〜ますか.",
    vocab: [
      { jp: "にく", romaji: "niku", en: "meat", pos: "n" },
      { jp: "おさけ", romaji: "osake", en: "alcohol / sake", pos: "n" },
      { jp: "まいにち", romaji: "mainichi", en: "every day", pos: "n" },
      { jp: "のみません", romaji: "nomimasen", en: "don't drink", pos: "v" },
      { jp: "たべません", romaji: "tabemasen", en: "don't eat", pos: "v" },
      { jp: "わかりません", romaji: "wakarimasen", en: "don't understand", pos: "v" },
    ],
    sentences: [
      { en: "Do you drink sake?", jp: "おさけを のみますか？", romaji: "osake o nomimasu ka?",
        words: [{jp:"おさけ",en:"sake",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "No, I don't drink.", jp: "いいえ、のみません。", romaji: "iie, nomimasen.",
        words: [{jp:"いいえ",en:"no",pos:"expr"},{jp:"のみません",en:"don't drink",pos:"v"}] },
      { en: "I don't eat meat.", jp: "にくを たべません。", romaji: "niku o tabemasen.", hint: "handy at restaurants",
        words: [{jp:"にく",en:"meat",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべません",en:"don't eat",pos:"v"}] },
      { en: "Do you go every day?", jp: "まいにち いきますか？", romaji: "mainichi ikimasu ka?",
        words: [{jp:"まいにち",en:"every day",pos:"n"},{jp:"いきます",en:"go",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Yes, I go.", jp: "はい、いきます。", romaji: "hai, ikimasu.",
        words: [{jp:"はい",en:"yes",pos:"expr"},{jp:"いきます",en:"go",pos:"v"}] },
      { en: "I don't understand.", jp: "わかりません。", romaji: "wakarimasen.", hint: "super useful!",
        words: [{jp:"わかりません",en:"don't understand",pos:"v"}] },
    ],
  },
  {
    id: "coming-going",
    section: "Level 3 · Doing things",
    title: "Coming & going (〜に いきます)",
    grammar: "[place]に いきます／きます／かえります",
    grammarNote:
      "Movement verbs take a destination marked with に: [place]に いきます = go to [place]. きます = come; かえります = return / go home.",
    vocab: [
      { jp: "がっこう", romaji: "gakkou", en: "school", pos: "n" },
      { jp: "うち", romaji: "uchi", en: "home / house", pos: "n" },
      { jp: "きます", romaji: "kimasu", en: "come  (来る)", pos: "v" },
      { jp: "かえります", romaji: "kaerimasu", en: "return / go home  (帰る)", pos: "v" },
      { jp: "あした", romaji: "ashita", en: "tomorrow", pos: "n" },
      { jp: "にほん", romaji: "nihon", en: "Japan", pos: "n" },
    ],
    sentences: [
      { en: "I go to school.", jp: "がっこうに いきます。", romaji: "gakkou ni ikimasu.",
        words: [{jp:"がっこう",en:"school",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
      { en: "I'm going home.", jp: "うちに かえります。", romaji: "uchi ni kaerimasu.",
        words: [{jp:"うち",en:"home",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"かえります",en:"go home",pos:"v"}] },
      { en: "Will you come tomorrow?", jp: "あした きますか？", romaji: "ashita kimasu ka?",
        words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"きます",en:"come",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Yes, I'll come.", jp: "はい、きます。", romaji: "hai, kimasu.",
        words: [{jp:"はい",en:"yes",pos:"expr"},{jp:"きます",en:"come",pos:"v"}] },
      { en: "I'm going to Japan.", jp: "にほんに いきます。", romaji: "nihon ni ikimasu.",
        words: [{jp:"にほん",en:"Japan",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
      { en: "I'll go home tomorrow.", jp: "あした うちに かえります。", romaji: "ashita uchi ni kaerimasu.",
        words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"うち",en:"home",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"かえります",en:"go home",pos:"v"}] },
    ],
  },

  // ============================================================
  // EVERYDAY LIFE
  // ============================================================
  {
    id: "routine",
    section: "Level 4 · Daily life",
    title: "My daily routine",
    grammar: "present 〜ます  ·  time に  ·  で (by)",
    grammarNote:
      "〜ます is the polite present — also used for habits and the near future. Put に after a clock time, and で after a means of transport.",
    vocab: [
      { jp: "まいあさ", romaji: "maiasa", en: "every morning", pos: "n" },
      { jp: "しちじ", romaji: "shichi-ji", en: "7 o'clock", pos: "n" },
      { jp: "でんしゃ", romaji: "densha", en: "train", pos: "n" },
      { jp: "しごと", romaji: "shigoto", en: "work", pos: "n" },
      { jp: "コーヒー", romaji: "koohii", en: "coffee", pos: "n" },
      { jp: "おきます", romaji: "okimasu", en: "wake up  (起きる)", pos: "v" },
      { jp: "のみます", romaji: "nomimasu", en: "drink  (飲む)", pos: "v" },
      { jp: "いきます", romaji: "ikimasu", en: "go  (行く)", pos: "v" },
    ],
    sentences: [
      { en: "I wake up at seven.", jp: "しちじに おきます。", romaji: "shichi-ji ni okimasu.", hint: "に after a clock time",
        words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"おきます",en:"wake up",pos:"v"}] },
      { en: "I drink coffee every morning.", jp: "まいあさ コーヒーを のみます。", romaji: "maiasa koohii o nomimasu.",
        words: [{jp:"まいあさ",en:"every morning",pos:"n"},{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
      { en: "I go to work by train.", jp: "でんしゃで しごとに いきます。", romaji: "densha de shigoto ni ikimasu.", hint: "で = by means of",
        words: [{jp:"でんしゃ",en:"train",pos:"n"},{jp:"で",en:"[by means of]",pos:"prt"},{jp:"しごと",en:"work",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
      { en: "I go to work at seven.", jp: "しちじに しごとに いきます。", romaji: "shichi-ji ni shigoto ni ikimasu.",
        words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"しごと",en:"work",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
      { en: "Every morning I go by train.", jp: "まいあさ でんしゃで いきます。", romaji: "maiasa densha de ikimasu.",
        words: [{jp:"まいあさ",en:"every morning",pos:"n"},{jp:"でんしゃ",en:"train",pos:"n"},{jp:"で",en:"[by means of]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
      { en: "I drink coffee.", jp: "コーヒーを のみます。", romaji: "koohii o nomimasu.",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
    ],
  },
  {
    id: "telling-time",
    section: "Level 4 · Daily life",
    title: "Telling time (なんじ)",
    grammar: "いま なんじ  ·  〜じ・はん  ·  ごぜん／ごご",
    grammarNote:
      "Ask the time with いま なんじですか. Hours take 〜じ; はん = half past. ごぜん = AM, ごご = PM. Pin an action to a time with に.",
    vocab: [
      { jp: "いま", romaji: "ima", en: "now", pos: "n" },
      { jp: "なんじ", romaji: "nan-ji", en: "what time", pos: "n" },
      { jp: "はん", romaji: "han", en: "half (past)", pos: "n" },
      { jp: "ごぜん", romaji: "gozen", en: "AM", pos: "n" },
      { jp: "ごご", romaji: "gogo", en: "PM", pos: "n" },
      { jp: "ねます", romaji: "nemasu", en: "sleep / go to bed  (寝る)", pos: "v" },
    ],
    sentences: [
      { en: "What time is it now?", jp: "いま なんじですか？", romaji: "ima nan-ji desu ka?",
        words: [{jp:"いま",en:"now",pos:"n"},{jp:"なんじ",en:"what time",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "It's 7 o'clock.", jp: "しちじです。", romaji: "shichi-ji desu.",
        words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "It's half past 8.", jp: "はちじはんです。", romaji: "hachi-ji han desu.", hint: "はん = half past",
        words: [{jp:"はちじ",en:"8 o'clock",pos:"n"},{jp:"はん",en:"half past",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "I go to bed at 11.", jp: "じゅういちじに ねます。", romaji: "juuichi-ji ni nemasu.",
        words: [{jp:"じゅういちじ",en:"11 o'clock",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"ねます",en:"sleep",pos:"v"}] },
      { en: "I wake up at 6 AM.", jp: "ごぜん ろくじに おきます。", romaji: "gozen roku-ji ni okimasu.",
        words: [{jp:"ごぜん",en:"AM",pos:"n"},{jp:"ろくじ",en:"6 o'clock",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"おきます",en:"wake up",pos:"v"}] },
      { en: "Work is at 9.", jp: "しごとは くじです。", romaji: "shigoto wa ku-ji desu.",
        words: [{jp:"しごと",en:"work",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"くじ",en:"9 o'clock",pos:"n"},{jp:"です",en:"is",pos:"cop"}] },
    ],
  },
  {
    id: "frequency",
    section: "Level 4 · Daily life",
    title: "How often (よく・ときどき)",
    grammar: "よく・ときどき  ·  あまり／ぜんぜん 〜ません",
    grammarNote:
      "Frequency words sit before the verb: よく = often, ときどき = sometimes. あまり and ぜんぜん pair with a negative verb — あまり〜ません = not much, ぜんぜん〜ません = not at all.",
    vocab: [
      { jp: "よく", romaji: "yoku", en: "often", pos: "adv" },
      { jp: "ときどき", romaji: "tokidoki", en: "sometimes", pos: "adv" },
      { jp: "あまり", romaji: "amari", en: "not much (+ neg)", pos: "adv" },
      { jp: "ぜんぜん", romaji: "zenzen", en: "not at all (+ neg)", pos: "adv" },
      { jp: "テレビ", romaji: "terebi", en: "TV", pos: "n" },
      { jp: "べんきょうします", romaji: "benkyou-shimasu", en: "study  (勉強する)", pos: "v" },
    ],
    sentences: [
      { en: "I often watch TV.", jp: "よく テレビを みます。", romaji: "yoku terebi o mimasu.",
        words: [{jp:"よく",en:"often",pos:"adv"},{jp:"テレビ",en:"TV",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みます",en:"watch",pos:"v"}] },
      { en: "I sometimes drink coffee.", jp: "ときどき コーヒーを のみます。", romaji: "tokidoki koohii o nomimasu.",
        words: [{jp:"ときどき",en:"sometimes",pos:"adv"},{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
      { en: "I don't watch much.", jp: "あまり みません。", romaji: "amari mimasen.", hint: "あまり needs a negative verb",
        words: [{jp:"あまり",en:"not much",pos:"adv"},{jp:"みません",en:"don't watch",pos:"v"}] },
      { en: "I don't drink at all.", jp: "ぜんぜん のみません。", romaji: "zenzen nomimasen.",
        words: [{jp:"ぜんぜん",en:"not at all",pos:"adv"},{jp:"のみません",en:"don't drink",pos:"v"}] },
      { en: "Do you go often?", jp: "よく いきますか？", romaji: "yoku ikimasu ka?",
        words: [{jp:"よく",en:"often",pos:"adv"},{jp:"いきます",en:"go",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "I study every day.", jp: "まいにち べんきょうします。", romaji: "mainichi benkyou-shimasu.",
        words: [{jp:"まいにち",en:"every day",pos:"n"},{jp:"べんきょうします",en:"study",pos:"v"}] },
    ],
  },
  {
    id: "activities",
    section: "Level 4 · Daily life",
    title: "Where you do it (〜で)",
    grammar: "[place]で [verb]  ·  あさ／よる",
    grammarNote:
      "で also marks WHERE an action happens: [place]で [verb]. (Same particle as “by train” — both uses share で.) あさ = morning, よる = night.",
    vocab: [
      { jp: "かいしゃ", romaji: "kaisha", en: "company / office", pos: "n" },
      { jp: "はたらきます", romaji: "hatarakimasu", en: "work  (働く)", pos: "v" },
      { jp: "あさ", romaji: "asa", en: "morning", pos: "n" },
      { jp: "よる", romaji: "yoru", en: "night / evening", pos: "n" },
      { jp: "うち", romaji: "uchi", en: "home / house", pos: "n" },
      { jp: "なに", romaji: "nani", en: "what", pos: "n" },
    ],
    sentences: [
      { en: "I work at a company.", jp: "かいしゃで はたらきます。", romaji: "kaisha de hatarakimasu.", hint: "で = at (where the action happens)",
        words: [{jp:"かいしゃ",en:"company",pos:"n"},{jp:"で",en:"[at]",pos:"prt"},{jp:"はたらきます",en:"work",pos:"v"}] },
      { en: "I study at home.", jp: "うちで べんきょうします。", romaji: "uchi de benkyou-shimasu.",
        words: [{jp:"うち",en:"home",pos:"n"},{jp:"で",en:"[at]",pos:"prt"},{jp:"べんきょうします",en:"study",pos:"v"}] },
      { en: "I eat in the morning.", jp: "あさ ごはんを たべます。", romaji: "asa gohan o tabemasu.",
        words: [{jp:"あさ",en:"morning",pos:"n"},{jp:"ごはん",en:"meal",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべます",en:"eat",pos:"v"}] },
      { en: "I watch TV at night.", jp: "よる テレビを みます。", romaji: "yoru terebi o mimasu.",
        words: [{jp:"よる",en:"night",pos:"n"},{jp:"テレビ",en:"TV",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みます",en:"watch",pos:"v"}] },
      { en: "I sleep at home.", jp: "うちで ねます。", romaji: "uchi de nemasu.",
        words: [{jp:"うち",en:"home",pos:"n"},{jp:"で",en:"[at]",pos:"prt"},{jp:"ねます",en:"sleep",pos:"v"}] },
      { en: "What do you do at the office?", jp: "かいしゃで なにを しますか？", romaji: "kaisha de nani o shimasu ka?",
        words: [{jp:"かいしゃ",en:"company",pos:"n"},{jp:"で",en:"[at]",pos:"prt"},{jp:"なに",en:"what",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"します",en:"do",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
    ],
  },
  {
    id: "past-1",
    section: "Level 5 · The past",
    title: "What did you do yesterday?",
    grammar: "past 〜ました  ·  を / に / と",
    grammarNote:
      "For the past, the polite ending becomes 〜ました. Mark the thing you act on with を, the person you meet with に, and “together with” someone with と.",
    vocab: [
      { jp: "きのう", romaji: "kinou", en: "yesterday", pos: "n" },
      { jp: "ともだち", romaji: "tomodachi", en: "friend", pos: "n" },
      { jp: "えいが", romaji: "eiga", en: "movie", pos: "n" },
      { jp: "ごはん", romaji: "gohan", en: "meal / food", pos: "n" },
      { jp: "なに", romaji: "nani", en: "what", pos: "n" },
      { jp: "だれ", romaji: "dare", en: "who", pos: "n" },
      { jp: "みました", romaji: "mimashita", en: "watched / saw  (見る)", pos: "v" },
      { jp: "あいました", romaji: "aimashita", en: "met  (会う)", pos: "v" },
      { jp: "たべました", romaji: "tabemashita", en: "ate  (食べる)", pos: "v" },
    ],
    sentences: [
      { en: "Yesterday I watched a movie.", jp: "きのう えいがを みました。", romaji: "kinou eiga o mimashita.", hint: "を marks the thing you watched",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"えいが",en:"movie",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みました",en:"watched",pos:"v"}] },
      { en: "Yesterday I met a friend.", jp: "きのう ともだちに あいました。", romaji: "kinou tomodachi ni aimashita.", hint: "あう takes に for the person",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"ともだち",en:"friend",pos:"n"},{jp:"に",en:"[with person]",pos:"prt"},{jp:"あいました",en:"met",pos:"v"}] },
      { en: "Yesterday I ate a meal.", jp: "きのう ごはんを たべました。", romaji: "kinou gohan o tabemashita.",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"ごはん",en:"meal / food",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべました",en:"ate",pos:"v"}] },
      { en: "I watched a movie with a friend.", jp: "ともだちと えいがを みました。", romaji: "tomodachi to eiga o mimashita.", hint: "と = (together) with",
        words: [{jp:"ともだち",en:"friend",pos:"n"},{jp:"と",en:"with",pos:"prt"},{jp:"えいが",en:"movie",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みました",en:"watched",pos:"v"}] },
      { en: "I ate a meal with a friend.", jp: "ともだちと ごはんを たべました。", romaji: "tomodachi to gohan o tabemashita.",
        words: [{jp:"ともだち",en:"friend",pos:"n"},{jp:"と",en:"with",pos:"prt"},{jp:"ごはん",en:"meal / food",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべました",en:"ate",pos:"v"}] },
      { en: "What did you watch yesterday?", jp: "きのう なにを みましたか？", romaji: "kinou nani o mimashita ka?", hint: "なに = what",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"なに",en:"what",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みました",en:"watched",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Who did you meet yesterday?", jp: "きのう だれに あいましたか？", romaji: "kinou dare ni aimashita ka?", hint: "だれ = who",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"だれ",en:"who",pos:"n"},{jp:"に",en:"[with person]",pos:"prt"},{jp:"あいました",en:"met",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "Yesterday I watched a movie with a friend.", jp: "きのう ともだちと えいがを みました。", romaji: "kinou tomodachi to eiga o mimashita.", hint: "putting it all together",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"ともだち",en:"friend",pos:"n"},{jp:"と",en:"with",pos:"prt"},{jp:"えいが",en:"movie",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みました",en:"watched",pos:"v"}] },
    ],
  },
  {
    id: "past-negative",
    section: "Level 5 · The past",
    title: "Didn't do it (〜ませんでした)",
    grammar: "〜ませんでした (didn't)  ·  なにも + neg",
    grammarNote:
      "The past negative is 〜ませんでした (“didn't”). Add か for a past question: 〜ましたか. なにも + a negative verb = “nothing”.",
    vocab: [
      { jp: "せんしゅう", romaji: "senshuu", en: "last week", pos: "n" },
      { jp: "なにも", romaji: "nani mo", en: "nothing (+ neg)", pos: "n" },
      { jp: "かいました", romaji: "kaimashita", en: "bought  (買う)", pos: "v" },
      { jp: "いきませんでした", romaji: "ikimasen deshita", en: "didn't go", pos: "v" },
      { jp: "しました", romaji: "shimashita", en: "did  (する)", pos: "v" },
      { jp: "ほん", romaji: "hon", en: "book", pos: "n" },
    ],
    sentences: [
      { en: "Did you go yesterday?", jp: "きのう いきましたか？", romaji: "kinou ikimashita ka?",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"いきました",en:"went",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "No, I didn't go.", jp: "いいえ、いきませんでした。", romaji: "iie, ikimasen deshita.",
        words: [{jp:"いいえ",en:"no",pos:"expr"},{jp:"いきませんでした",en:"didn't go",pos:"v"}] },
      { en: "I didn't eat anything.", jp: "なにも たべませんでした。", romaji: "nani mo tabemasen deshita.", hint: "なにも + negative = nothing",
        words: [{jp:"なにも",en:"nothing",pos:"n"},{jp:"たべませんでした",en:"didn't eat",pos:"v"}] },
      { en: "What did you do last week?", jp: "せんしゅう なにを しましたか？", romaji: "senshuu nani o shimashita ka?",
        words: [{jp:"せんしゅう",en:"last week",pos:"n"},{jp:"なに",en:"what",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"しました",en:"did",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "I bought a book.", jp: "ほんを かいました。", romaji: "hon o kaimashita.",
        words: [{jp:"ほん",en:"book",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"かいました",en:"bought",pos:"v"}] },
      { en: "I didn't do anything.", jp: "なにも しませんでした。", romaji: "nani mo shimasen deshita.",
        words: [{jp:"なにも",en:"nothing",pos:"n"},{jp:"しませんでした",en:"didn't do",pos:"v"}] },
    ],
  },
  {
    id: "was-were",
    section: "Level 5 · The past",
    title: "It was… (でした)",
    grammar: "でした (was/were)  ·  〜じゃ ありませんでした",
    grammarNote:
      "The past of です is でした (“was / were”). For “wasn't,” use 〜じゃ ありませんでした. These work with nouns, not verbs.",
    vocab: [
      { jp: "でした", romaji: "deshita", en: "was / were", pos: "cop" },
      { jp: "やすみ", romaji: "yasumi", en: "day off / holiday", pos: "n" },
      { jp: "せんせい", romaji: "sensei", en: "teacher", pos: "n" },
      { jp: "じゃ ありませんでした", romaji: "ja arimasen deshita", en: "was not", pos: "cop" },
      { jp: "おすし", romaji: "osushi", en: "sushi", pos: "n" },
      { jp: "きのう", romaji: "kinou", en: "yesterday", pos: "n" },
    ],
    sentences: [
      { en: "Yesterday was a day off.", jp: "きのうは やすみでした。", romaji: "kinou wa yasumi deshita.",
        words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"やすみ",en:"day off",pos:"n"},{jp:"でした",en:"was",pos:"cop"}] },
      { en: "It was sushi.", jp: "おすしでした。", romaji: "osushi deshita.",
        words: [{jp:"おすし",en:"sushi",pos:"n"},{jp:"でした",en:"was",pos:"cop"}] },
      { en: "It was 500 yen.", jp: "ごひゃくえんでした。", romaji: "gohyaku-en deshita.",
        words: [{jp:"ごひゃく",en:"500",pos:"n"},{jp:"えん",en:"yen",pos:"n"},{jp:"でした",en:"was",pos:"cop"}] },
      { en: "It wasn't water.", jp: "みずじゃ ありませんでした。", romaji: "mizu ja arimasen deshita.", hint: "じゃ ありませんでした = wasn't",
        words: [{jp:"みず",en:"water",pos:"n"},{jp:"じゃ ありませんでした",en:"was not",pos:"cop"}] },
      { en: "Was it coffee?", jp: "コーヒーでしたか？", romaji: "koohii deshita ka?",
        words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"でした",en:"was",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
      { en: "(She) was a teacher.", jp: "せんせいでした。", romaji: "sensei deshita.",
        words: [{jp:"せんせい",en:"teacher",pos:"n"},{jp:"でした",en:"was",pos:"cop"}] },
    ],
  },
  {
    id: "sequence",
    section: "Level 5 · The past",
    title: "And then… (それから)",
    grammar: "それから (and then)  ·  chaining 〜ました",
    grammarNote:
      "Tell a story in order with それから (“after that / then”). Each step stays a full 〜ました sentence — no fancy conjugation needed yet.",
    vocab: [
      { jp: "それから", romaji: "sorekara", en: "and then", pos: "conj" },
      { jp: "あさごはん", romaji: "asa-gohan", en: "breakfast", pos: "n" },
      { jp: "ばんごはん", romaji: "ban-gohan", en: "dinner", pos: "n" },
      { jp: "こうえん", romaji: "kouen", en: "park", pos: "n" },
      { jp: "かえりました", romaji: "kaerimashita", en: "went home  (帰る)", pos: "v" },
      { jp: "ねました", romaji: "nemashita", en: "went to bed  (寝る)", pos: "v" },
    ],
    sentences: [
      { en: "I woke up at 7.", jp: "しちじに おきました。", romaji: "shichi-ji ni okimashita.",
        words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"おきました",en:"woke up",pos:"v"}] },
      { en: "And then I ate breakfast.", jp: "それから あさごはんを たべました。", romaji: "sorekara asa-gohan o tabemashita.", hint: "それから = and then",
        words: [{jp:"それから",en:"and then",pos:"conj"},{jp:"あさごはん",en:"breakfast",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべました",en:"ate",pos:"v"}] },
      { en: "I went to the park.", jp: "こうえんに いきました。", romaji: "kouen ni ikimashita.",
        words: [{jp:"こうえん",en:"park",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきました",en:"went",pos:"v"}] },
      { en: "And then I went home.", jp: "それから うちに かえりました。", romaji: "sorekara uchi ni kaerimashita.",
        words: [{jp:"それから",en:"and then",pos:"conj"},{jp:"うち",en:"home",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"かえりました",en:"went home",pos:"v"}] },
      { en: "I ate dinner.", jp: "ばんごはんを たべました。", romaji: "ban-gohan o tabemashita.",
        words: [{jp:"ばんごはん",en:"dinner",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべました",en:"ate",pos:"v"}] },
      { en: "And then I went to bed.", jp: "それから ねました。", romaji: "sorekara nemashita.",
        words: [{jp:"それから",en:"and then",pos:"conj"},{jp:"ねました",en:"went to bed",pos:"v"}] },
    ],
  },
  {
    id: "wants",
    section: "Level 6 · Wants & plans",
    title: "What I want to do",
    grammar: "〜たい (want to)  ·  〜が ほしい (want a thing)",
    grammarNote:
      "Verb-stem + たい says you want to DO something (のむ → のみたい). For wanting a THING (a noun), use [thing] が ほしい.",
    vocab: [
      { jp: "にほん", romaji: "nihon", en: "Japan", pos: "n" },
      { jp: "おすし", romaji: "osushi", en: "sushi", pos: "n" },
      { jp: "くるま", romaji: "kuruma", en: "car", pos: "n" },
      { jp: "いきたい", romaji: "ikitai", en: "want to go", pos: "v" },
      { jp: "たべたい", romaji: "tabetai", en: "want to eat", pos: "v" },
      { jp: "やすみたい", romaji: "yasumitai", en: "want to rest", pos: "v" },
      { jp: "ほしい", romaji: "hoshii", en: "want (a thing)", pos: "adj" },
    ],
    sentences: [
      { en: "I want to go to Japan.", jp: "にほんに いきたいです。", romaji: "nihon ni ikitai desu.", hint: "に marks the destination",
        words: [{jp:"にほん",en:"Japan",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきたい",en:"want to go",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "I want to eat sushi.", jp: "おすしが たべたいです。", romaji: "osushi ga tabetai desu.",
        words: [{jp:"おすし",en:"sushi",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"たべたい",en:"want to eat",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "I want to rest.", jp: "やすみたいです。", romaji: "yasumitai desu.",
        words: [{jp:"やすみたい",en:"want to rest",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "I want a car.", jp: "くるまが ほしいです。", romaji: "kuruma ga hoshii desu.", hint: "が ほしい = want a thing",
        words: [{jp:"くるま",en:"car",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ほしい",en:"want (a thing)",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "I want to eat sushi in Japan.", jp: "にほんで おすしが たべたいです。", romaji: "nihon de osushi ga tabetai desu.", hint: "で = at/in (where it happens)",
        words: [{jp:"にほん",en:"Japan",pos:"n"},{jp:"で",en:"[in / at]",pos:"prt"},{jp:"おすし",en:"sushi",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"たべたい",en:"want to eat",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "I want to go by car.", jp: "くるまで いきたいです。", romaji: "kuruma de ikitai desu.",
        words: [{jp:"くるま",en:"car",pos:"n"},{jp:"で",en:"[by means of]",pos:"prt"},{jp:"いきたい",en:"want to go",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
    ],
  },

  // ============================================================
  // DESCRIBING THINGS
  // ============================================================
  {
    id: "adjectives",
    section: "Level 7 · Describing things",
    title: "Describing things (い-adjectives)",
    grammar: "い-adjectives  ·  past 〜かった",
    grammarNote:
      "い-adjectives end in 〜い (たかい = expensive). For the past, drop the い and add 〜かった (たかかった = was expensive). とても = very.",
    vocab: [
      { jp: "えいが", romaji: "eiga", en: "movie", pos: "n" },
      { jp: "りょこう", romaji: "ryokou", en: "trip", pos: "n" },
      { jp: "とても", romaji: "totemo", en: "very", pos: "adv" },
      { jp: "たかい", romaji: "takai", en: "expensive / high", pos: "adj" },
      { jp: "おいしい", romaji: "oishii", en: "delicious", pos: "adj" },
      { jp: "たのしい", romaji: "tanoshii", en: "fun / enjoyable", pos: "adj" },
    ],
    sentences: [
      { en: "It's very delicious.", jp: "とても おいしいです。", romaji: "totemo oishii desu.", hint: "とても = very",
        words: [{jp:"とても",en:"very",pos:"adv"},{jp:"おいしい",en:"delicious",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "The movie is fun.", jp: "えいがは たのしいです。", romaji: "eiga wa tanoshii desu.",
        words: [{jp:"えいが",en:"movie",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"たのしい",en:"fun",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
      { en: "The trip was fun.", jp: "りょこうは たのしかったです。", romaji: "ryokou wa tanoshikatta desu.", hint: "past: い → かった",
        words: [{jp:"りょこう",en:"trip",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"たのしかった",en:"was fun",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "The movie was expensive.", jp: "えいがは たかかったです。", romaji: "eiga wa takakatta desu.",
        words: [{jp:"えいが",en:"movie",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"たかかった",en:"was expensive",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "It was very delicious.", jp: "とても おいしかったです。", romaji: "totemo oishikatta desu.",
        words: [{jp:"とても",en:"very",pos:"adv"},{jp:"おいしかった",en:"was delicious",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
      { en: "The trip was very fun.", jp: "りょこうは とても たのしかったです。", romaji: "ryokou wa totemo tanoshikatta desu.", hint: "putting it all together",
        words: [{jp:"りょこう",en:"trip",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"とても",en:"very",pos:"adv"},{jp:"たのしかった",en:"was fun",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
    ],
  },
];
