// Prompt & Respond drills — conversational Japanese.
// Each prompt: { id, level (1-5), en, jp, romaji, hint?, words: [{jp,en,pos}] }
//
// pos values used by the UI to color-code each word chip:
//   n=noun, v=verb, adj=adjective, adv=adverb, prt=particle,
//   cop=copula(です/だ), expr=fixed expression/greeting,
//   aux=auxiliary (ください, ました, たい, ましょう, かもしれません…),
//   conj=conjunction (から, ので, とき, まえに…)

window.PROMPTS = [
  // ============================================================
  // Level 1 — Survival
  // ============================================================
  { id: 101, level: 1, en: "Greet someone in the morning.", jp: "おはよう ございます。", romaji: "ohayou gozaimasu.", hint: "polite morning greeting",
    words: [{jp:"おはよう",en:"good morning",pos:"expr"},{jp:"ございます",en:"[polite]",pos:"aux"}] },
  { id: 110, level: 1, en: "Greet someone in the daytime.", jp: "こんにちは。", romaji: "konnichiwa.", hint: "general 'hello'",
    words: [{jp:"こんにちは",en:"hello / good day",pos:"expr"}] },
  { id: 111, level: 1, en: "Greet someone in the evening.", jp: "こんばんは。", romaji: "konbanwa.",
    words: [{jp:"こんばんは",en:"good evening",pos:"expr"}] },
  { id: 112, level: 1, en: "Say good night.", jp: "おやすみなさい。", romaji: "oyasumi nasai.",
    words: [{jp:"おやすみなさい",en:"good night",pos:"expr"}] },
  { id: 113, level: 1, en: "Say goodbye (formal).", jp: "さようなら。", romaji: "sayounara.",
    words: [{jp:"さようなら",en:"goodbye",pos:"expr"}] },
  { id: 114, level: 1, en: "Say: See you tomorrow.", jp: "また あした。", romaji: "mata ashita.",
    words: [{jp:"また",en:"again / see you",pos:"adv"},{jp:"あした",en:"tomorrow",pos:"n"}] },
  { id: 102, level: 1, en: "Say: Nice to meet you.", jp: "はじめまして。", romaji: "hajimemashite.", hint: "used on first meeting",
    words: [{jp:"はじめまして",en:"nice to meet you",pos:"expr"}] },
  { id: 103, level: 1, en: "Say thank you (politely).", jp: "ありがとう ございます。", romaji: "arigatou gozaimasu.",
    words: [{jp:"ありがとう",en:"thank you",pos:"expr"},{jp:"ございます",en:"[polite]",pos:"aux"}] },
  { id: 104, level: 1, en: "Say: Excuse me / I'm sorry.", jp: "すみません。", romaji: "sumimasen.", hint: "all-purpose excuse me",
    words: [{jp:"すみません",en:"excuse me / sorry",pos:"expr"}] },
  { id: 141, level: 1, en: "Apologize sincerely.", jp: "ごめんなさい。", romaji: "gomen nasai.",
    words: [{jp:"ごめんなさい",en:"I'm sorry",pos:"expr"}] },
  { id: 115, level: 1, en: "Say yes.", jp: "はい。", romaji: "hai.",
    words: [{jp:"はい",en:"yes",pos:"expr"}] },
  { id: 116, level: 1, en: "Say no.", jp: "いいえ。", romaji: "iie.",
    words: [{jp:"いいえ",en:"no",pos:"expr"}] },
  { id: 105, level: 1, en: "Say: I am American.", jp: "わたしは アメリカじんです。", romaji: "watashi wa amerika-jin desu.", hint: "~じん = ___-person",
    words: [{jp:"わたし",en:"I / me",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"アメリカじん",en:"American",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 117, level: 1, en: "Say: My name is Tom.", jp: "わたしは トムです。", romaji: "watashi wa Tomu desu.",
    words: [{jp:"わたし",en:"I",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"トム",en:"Tom",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 135, level: 1, en: "Ask: What's your name?", jp: "おなまえは なんですか？", romaji: "onamae wa nan desu ka?",
    words: [{jp:"おなまえ",en:"(your) name",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"なん",en:"what",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 118, level: 1, en: "Say: I'm a student.", jp: "がくせいです。", romaji: "gakusei desu.",
    words: [{jp:"がくせい",en:"student",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 119, level: 1, en: "Say: I'm thirty-five years old.", jp: "さんじゅうごさいです。", romaji: "sanjuugo-sai desu.",
    words: [{jp:"さんじゅうご",en:"35",pos:"n"},{jp:"さい",en:"years old",pos:"n"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 133, level: 1, en: "Ask: How are you?", jp: "おげんきですか？", romaji: "ogenki desu ka?",
    words: [{jp:"おげんき",en:"(your) health",pos:"n"},{jp:"です",en:"are",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 132, level: 1, en: "Reply: I'm fine, thanks.", jp: "げんきです。", romaji: "genki desu.",
    words: [{jp:"げんき",en:"fine / well",pos:"adj"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 1, level: 1, en: "Ask what time it is now.", jp: "いま なんじですか？", romaji: "ima nanji desu ka?", hint: "いま = now",
    words: [{jp:"いま",en:"now",pos:"adv"},{jp:"なんじ",en:"what time",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 6, level: 1, en: "Ask: Where is the station?", jp: "えきは どこですか？", romaji: "eki wa doko desu ka?",
    words: [{jp:"えき",en:"station",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"どこ",en:"where",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 134, level: 1, en: "Ask: Where is the bathroom?", jp: "トイレは どこですか？", romaji: "toire wa doko desu ka?",
    words: [{jp:"トイレ",en:"toilet / bathroom",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"どこ",en:"where",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 11, level: 1, en: "Ask: How much is this?", jp: "これは いくらですか？", romaji: "kore wa ikura desu ka?",
    words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いくら",en:"how much",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 106, level: 1, en: "Ask: What is this?", jp: "これは なんですか？", romaji: "kore wa nan desu ka?",
    words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"なん",en:"what",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 16, level: 1, en: "Politely decline: No thank you, I'm fine.", jp: "いいえ、けっこうです。", romaji: "iie, kekkou desu.",
    words: [{jp:"いいえ",en:"no",pos:"expr"},{jp:"けっこう",en:"fine / enough",pos:"adj"},{jp:"です",en:"[it] is",pos:"cop"}] },
  { id: 121, level: 1, en: "Say: Please (when requesting something).", jp: "おねがいします。", romaji: "onegai shimasu.",
    words: [{jp:"おねがい",en:"a request",pos:"n"},{jp:"します",en:"do",pos:"v"}] },
  { id: 126, level: 1, en: "Order: A menu, please.", jp: "メニューを おねがいします。", romaji: "menyuu o onegai shimasu.",
    words: [{jp:"メニュー",en:"menu",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"おねがいします",en:"please / I request",pos:"expr"}] },
  { id: 127, level: 1, en: "Order: One beer, please.", jp: "ビールを ひとつ おねがいします。", romaji: "biiru o hitotsu onegai shimasu.",
    words: [{jp:"ビール",en:"beer",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ひとつ",en:"one",pos:"n"},{jp:"おねがいします",en:"please",pos:"expr"}] },
  { id: 128, level: 1, en: "Ask for the bill.", jp: "おかいけい おねがいします。", romaji: "okaikei onegai shimasu.",
    words: [{jp:"おかいけい",en:"the bill / check",pos:"n"},{jp:"おねがいします",en:"please",pos:"expr"}] },
  { id: 129, level: 1, en: "Say: It's delicious.", jp: "おいしいです。", romaji: "oishii desu.",
    words: [{jp:"おいしい",en:"delicious",pos:"adj"},{jp:"です",en:"[it] is",pos:"cop"}] },
  { id: 130, level: 1, en: "Say: It's hot today.", jp: "きょうは あついです。", romaji: "kyou wa atsui desu.",
    words: [{jp:"きょう",en:"today",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"あつい",en:"hot",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 131, level: 1, en: "Say: It's cold today.", jp: "きょうは さむいです。", romaji: "kyou wa samui desu.",
    words: [{jp:"きょう",en:"today",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"さむい",en:"cold",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 124, level: 1, en: "Say: I don't understand.", jp: "わかりません。", romaji: "wakarimasen.",
    words: [{jp:"わかりません",en:"don't understand",pos:"v"}] },
  { id: 140, level: 1, en: "Say: Got it / I understand.", jp: "わかりました。", romaji: "wakarimashita.",
    words: [{jp:"わかりました",en:"understood",pos:"v"}] },
  { id: 125, level: 1, en: "Ask: One more time, please.", jp: "もういちど おねがいします。", romaji: "mou ichido onegai shimasu.",
    words: [{jp:"もう",en:"one more",pos:"adv"},{jp:"いちど",en:"once / one time",pos:"n"},{jp:"おねがいします",en:"please",pos:"expr"}] },
  { id: 142, level: 1, en: "Say: Just a moment, please.", jp: "ちょっと まって ください。", romaji: "chotto matte kudasai.",
    words: [{jp:"ちょっと",en:"a moment / a little",pos:"adv"},{jp:"まって",en:"wait (te-form)",pos:"v"},{jp:"ください",en:"please",pos:"aux"}] },
  { id: 149, level: 1, en: "Say: It's OK / no problem.", jp: "だいじょうぶです。", romaji: "daijoubu desu.",
    words: [{jp:"だいじょうぶ",en:"OK / fine",pos:"adj"},{jp:"です",en:"[it] is",pos:"cop"}] },
  { id: 137, level: 1, en: "Confirm: That's right.", jp: "そうです。", romaji: "sou desu.",
    words: [{jp:"そう",en:"so / that way",pos:"adv"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 145, level: 1, en: "React positively: That sounds good.", jp: "いいですね。", romaji: "ii desu ne.",
    words: [{jp:"いい",en:"good / nice",pos:"adj"},{jp:"です",en:"is",pos:"cop"},{jp:"ね",en:"[right?]",pos:"prt"}] },
  { id: 146, level: 1, en: "React: Really?", jp: "ほんとうですか？", romaji: "hontou desu ka?",
    words: [{jp:"ほんとう",en:"truth / really",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 147, level: 1, en: "React: I see / oh I get it.", jp: "なるほど。", romaji: "naruhodo.",
    words: [{jp:"なるほど",en:"I see / makes sense",pos:"expr"}] },
  { id: 143, level: 1, en: "Toast: Cheers!", jp: "かんぱい！", romaji: "kanpai!",
    words: [{jp:"かんぱい",en:"cheers!",pos:"expr"}] },
  { id: 144, level: 1, en: "Say: Thanks for your hard work. (leaving work)", jp: "おつかれさまでした。", romaji: "otsukaresama deshita.",
    words: [{jp:"おつかれさま",en:"(your) tiredness — thanks for your work",pos:"expr"},{jp:"でした",en:"was [polite past]",pos:"cop"}] },

  // ============================================================
  // Level 2 — Daily polite
  // ============================================================
  { id: 201, level: 2, en: "Say: I wake up at seven.", jp: "しちじに おきます。", romaji: "shichi-ji ni okimasu.",
    words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"おきます",en:"wake up",pos:"v"}] },
  { id: 202, level: 2, en: "Say: I go to work by train.", jp: "でんしゃで しごとに いきます。", romaji: "densha de shigoto ni ikimasu.", hint: "で = by means of",
    words: [{jp:"でんしゃ",en:"train",pos:"n"},{jp:"で",en:"[by means of]",pos:"prt"},{jp:"しごと",en:"work",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
  { id: 203, level: 2, en: "Say: I eat lunch at noon.", jp: "じゅうにじに おひるごはんを たべます。", romaji: "juuni-ji ni ohirugohan o tabemasu.",
    words: [{jp:"じゅうにじ",en:"12 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"おひるごはん",en:"lunch",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべます",en:"eat",pos:"v"}] },
  { id: 204, level: 2, en: "Say: I come home at seven.", jp: "しちじに うちに かえります。", romaji: "shichi-ji ni uchi ni kaerimasu.",
    words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"うち",en:"home",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"かえります",en:"return / go home",pos:"v"}] },
  { id: 205, level: 2, en: "Say: I go to bed at eleven.", jp: "じゅういちじに ねます。", romaji: "juuichi-ji ni nemasu.",
    words: [{jp:"じゅういちじ",en:"11 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"ねます",en:"sleep / go to bed",pos:"v"}] },
  { id: 206, level: 2, en: "Say: I drink coffee every morning.", jp: "まいあさ コーヒーを のみます。", romaji: "maiasa koohii o nomimasu.",
    words: [{jp:"まいあさ",en:"every morning",pos:"n"},{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
  { id: 207, level: 2, en: "Say: I read books on weekends.", jp: "しゅうまつに ほんを よみます。", romaji: "shuumatsu ni hon o yomimasu.",
    words: [{jp:"しゅうまつ",en:"weekend",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"ほん",en:"book",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"よみます",en:"read",pos:"v"}] },
  { id: 5, level: 2, en: "Say: I ate breakfast this morning.", jp: "けさ あさごはんを たべました。", romaji: "kesa asagohan o tabemashita.",
    words: [{jp:"けさ",en:"this morning",pos:"n"},{jp:"あさごはん",en:"breakfast",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべました",en:"ate [past]",pos:"v"}] },
  { id: 208, level: 2, en: "Say: I watched a movie yesterday.", jp: "きのう えいがを みました。", romaji: "kinou eiga o mimashita.",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"えいが",en:"movie",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みました",en:"watched",pos:"v"}] },
  { id: 209, level: 2, en: "Say: I bought new shoes.", jp: "あたらしい くつを かいました。", romaji: "atarashii kutsu o kaimashita.",
    words: [{jp:"あたらしい",en:"new",pos:"adj"},{jp:"くつ",en:"shoes",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"かいました",en:"bought",pos:"v"}] },
  { id: 210, level: 2, en: "Say: I met a friend yesterday.", jp: "きのう ともだちに あいました。", romaji: "kinou tomodachi ni aimashita.", hint: "に person + あう = meet ___",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"ともだち",en:"friend",pos:"n"},{jp:"に",en:"[with person]",pos:"prt"},{jp:"あいました",en:"met",pos:"v"}] },
  { id: 211, level: 2, en: "Say: I called my mother.", jp: "ははに でんわしました。", romaji: "haha ni denwa shimashita.",
    words: [{jp:"はは",en:"(my) mother",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"でんわ",en:"phone call",pos:"n"},{jp:"しました",en:"did / made",pos:"v"}] },
  { id: 212, level: 2, en: "Say: I sent a message.", jp: "メッセージを おくりました。", romaji: "messeeji o okurimashita.",
    words: [{jp:"メッセージ",en:"message",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"おくりました",en:"sent",pos:"v"}] },
  { id: 213, level: 2, en: "Say: I wrote an email.", jp: "メールを かきました。", romaji: "meeru o kakimashita.",
    words: [{jp:"メール",en:"email",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"かきました",en:"wrote",pos:"v"}] },
  { id: 9, level: 2, en: "Say: I went to Tokyo yesterday.", jp: "きのう とうきょうに いきました。", romaji: "kinou Toukyou ni ikimashita.",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"とうきょう",en:"Tokyo",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきました",en:"went",pos:"v"}] },
  { id: 18, level: 2, en: "Ask: What did you do yesterday?", jp: "きのう なにを しましたか？", romaji: "kinou nani o shimashita ka?",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"なに",en:"what",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"しました",en:"did",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 214, level: 2, en: "Say: I don't drink coffee.", jp: "コーヒーを のみません。", romaji: "koohii o nomimasen.",
    words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみません",en:"don't drink",pos:"v"}] },
  { id: 216, level: 2, en: "Say: I don't know that person.", jp: "あの ひとを しりません。", romaji: "ano hito o shirimasen.",
    words: [{jp:"あの",en:"that (over there)",pos:"adj"},{jp:"ひと",en:"person",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"しりません",en:"don't know",pos:"v"}] },
  { id: 217, level: 2, en: "Say: I don't have any money.", jp: "おかねが ありません。", romaji: "okane ga arimasen.",
    words: [{jp:"おかね",en:"money",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ありません",en:"don't have / there isn't",pos:"v"}] },
  { id: 10, level: 2, en: "Say: I don't understand Japanese well.", jp: "にほんごが よく わかりません。", romaji: "nihongo ga yoku wakarimasen.",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"よく",en:"well",pos:"adv"},{jp:"わかりません",en:"don't understand",pos:"v"}] },
  { id: 14, level: 2, en: "Ask: Do you have time now?", jp: "いま じかんが ありますか？", romaji: "ima jikan ga arimasu ka?",
    words: [{jp:"いま",en:"now",pos:"adv"},{jp:"じかん",en:"time",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"あります",en:"have / there is",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 15, level: 2, en: "Say: My wife is at home.", jp: "つまは うちに います。", romaji: "tsuma wa uchi ni imasu.", hint: "います for people; あります for things",
    words: [{jp:"つま",en:"(my) wife",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"うち",en:"home",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"います",en:"is (animate)",pos:"v"}] },
  { id: 220, level: 2, en: "Say: Nice weather today, huh?", jp: "きょうは いい てんきですね。", romaji: "kyou wa ii tenki desu ne.", hint: "~ね = right? / huh",
    words: [{jp:"きょう",en:"today",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いい",en:"nice / good",pos:"adj"},{jp:"てんき",en:"weather",pos:"n"},{jp:"です",en:"is",pos:"cop"},{jp:"ね",en:"[right?]",pos:"prt"}] },
  { id: 7, level: 2, en: "Say: It's a little expensive.", jp: "ちょっと たかいです。", romaji: "chotto takai desu.",
    words: [{jp:"ちょっと",en:"a little",pos:"adv"},{jp:"たかい",en:"expensive / high",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 230, level: 2, en: "Say: It's not delicious.", jp: "おいしくないです。", romaji: "oishikunai desu.", hint: "i-adj negative: ~い → ~くない",
    words: [{jp:"おいしくない",en:"not delicious",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 232, level: 2, en: "Say: It wasn't fun.", jp: "たのしくなかったです。", romaji: "tanoshikunakatta desu.", hint: "i-adj negative past",
    words: [{jp:"たのしくなかった",en:"wasn't fun",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 233, level: 2, en: "Say: This book is interesting.", jp: "この ほんは おもしろいです。", romaji: "kono hon wa omoshiroi desu.",
    words: [{jp:"この",en:"this",pos:"adj"},{jp:"ほん",en:"book",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"おもしろい",en:"interesting",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 234, level: 2, en: "Say: My job is difficult.", jp: "しごとは むずかしいです。", romaji: "shigoto wa muzukashii desu.",
    words: [{jp:"しごと",en:"work / job",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"むずかしい",en:"difficult",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 235, level: 2, en: "Say: This restaurant is famous.", jp: "この レストランは ゆうめいです。", romaji: "kono resutoran wa yuumei desu.",
    words: [{jp:"この",en:"this",pos:"adj"},{jp:"レストラン",en:"restaurant",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ゆうめい",en:"famous",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 221, level: 2, en: "Say: I have a meeting at three.", jp: "さんじに かいぎが あります。", romaji: "san-ji ni kaigi ga arimasu.",
    words: [{jp:"さんじ",en:"3 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"かいぎ",en:"meeting",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"あります",en:"there is / have",pos:"v"}] },
  { id: 222, level: 2, en: "Say: I'll come at five.", jp: "ごじに きます。", romaji: "go-ji ni kimasu.",
    words: [{jp:"ごじ",en:"5 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"きます",en:"come / will come",pos:"v"}] },
  { id: 223, level: 2, en: "Say: I'll call you later.", jp: "あとで でんわします。", romaji: "ato de denwa shimasu.",
    words: [{jp:"あとで",en:"later",pos:"adv"},{jp:"でんわ",en:"phone call",pos:"n"},{jp:"します",en:"do / will do",pos:"v"}] },
  { id: 21, level: 2, en: "Say: I'll probably go tomorrow.", jp: "あした たぶん いきます。", romaji: "ashita tabun ikimasu.",
    words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"たぶん",en:"probably",pos:"adv"},{jp:"いきます",en:"go / will go",pos:"v"}] },
  { id: 224, level: 2, en: "Ask: Please give me water.", jp: "おみずを ください。", romaji: "omizu o kudasai.",
    words: [{jp:"おみず",en:"water",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"ください",en:"please give me",pos:"aux"}] },
  { id: 8, level: 2, en: "Politely ask: Could you say it one more time?", jp: "もういちど いって ください。", romaji: "mou ichido itte kudasai.",
    words: [{jp:"もういちど",en:"one more time",pos:"adv"},{jp:"いって",en:"say (te-form)",pos:"v"},{jp:"ください",en:"please",pos:"aux"}] },
  { id: 25, level: 2, en: "Politely ask: Could you speak a little more slowly?", jp: "もうすこし ゆっくり はなして ください。", romaji: "mou sukoshi yukkuri hanashite kudasai.",
    words: [{jp:"もうすこし",en:"a little more",pos:"adv"},{jp:"ゆっくり",en:"slowly",pos:"adv"},{jp:"はなして",en:"speak (te-form)",pos:"v"},{jp:"ください",en:"please",pos:"aux"}] },
  { id: 225, level: 2, en: "Politely ask: Please take a photo.", jp: "しゃしんを とって ください。", romaji: "shashin o totte kudasai.",
    words: [{jp:"しゃしん",en:"photo",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"とって",en:"take (te-form)",pos:"v"},{jp:"ください",en:"please",pos:"aux"}] },
  { id: 227, level: 2, en: "Politely ask: Please open the window.", jp: "まどを あけて ください。", romaji: "mado o akete kudasai.",
    words: [{jp:"まど",en:"window",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"あけて",en:"open (te-form)",pos:"v"},{jp:"ください",en:"please",pos:"aux"}] },
  { id: 229, level: 2, en: "Politely ask: Please show me.", jp: "みせて ください。", romaji: "misete kudasai.",
    words: [{jp:"みせて",en:"show (te-form)",pos:"v"},{jp:"ください",en:"please",pos:"aux"}] },
  { id: 239, level: 2, en: "Say: I forgot.", jp: "わすれました。", romaji: "wasuremashita.",
    words: [{jp:"わすれました",en:"forgot",pos:"v"}] },
  { id: 240, level: 2, en: "Say: I lost my wallet.", jp: "さいふを なくしました。", romaji: "saifu o nakushimashita.",
    words: [{jp:"さいふ",en:"wallet",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"なくしました",en:"lost",pos:"v"}] },
  { id: 242, level: 2, en: "Say: I'm tired.", jp: "つかれました。", romaji: "tsukaremashita.", hint: "literally 'I got tired' — used in present",
    words: [{jp:"つかれました",en:"got tired / I'm tired",pos:"v"}] },

  // ============================================================
  // Level 3 — Pimsleur ~4-5
  // ============================================================
  { id: 2, level: 3, en: "Say: I want to drink coffee.", jp: "コーヒーが のみたいです。", romaji: "koohii ga nomitai desu.", hint: "verb-stem + たい = want to ___",
    words: [{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"のみたい",en:"want to drink",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 3, level: 3, en: "Say: I would like to eat sushi.", jp: "おすしが たべたいです。", romaji: "osushi ga tabetai desu.",
    words: [{jp:"おすし",en:"sushi",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"たべたい",en:"want to eat",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 301, level: 3, en: "Say: I want to study Japanese.", jp: "にほんごを べんきょうしたいです。", romaji: "nihongo o benkyou shitai desu.",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"べんきょうしたい",en:"want to study",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 302, level: 3, en: "Say: I want to sleep.", jp: "ねたいです。", romaji: "netai desu.",
    words: [{jp:"ねたい",en:"want to sleep",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 303, level: 3, en: "Say: I want to rest.", jp: "やすみたいです。", romaji: "yasumitai desu.",
    words: [{jp:"やすみたい",en:"want to rest",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 305, level: 3, en: "Say: I want to learn more.", jp: "もっと まなびたいです。", romaji: "motto manabitai desu.",
    words: [{jp:"もっと",en:"more",pos:"adv"},{jp:"まなびたい",en:"want to learn",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 307, level: 3, en: "Say: I want to live in Japan.", jp: "にほんに すみたいです。", romaji: "nihon ni sumitai desu.",
    words: [{jp:"にほん",en:"Japan",pos:"n"},{jp:"に",en:"[in]",pos:"prt"},{jp:"すみたい",en:"want to live",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 12, level: 3, en: "Say: I'd like to go to a Japanese restaurant tonight.", jp: "こんばん にほんりょうりの レストランに いきたいです。", romaji: "konban nihonryouri no resutoran ni ikitai desu.",
    words: [{jp:"こんばん",en:"tonight",pos:"n"},{jp:"にほんりょうり",en:"Japanese cuisine",pos:"n"},{jp:"の",en:"[of]",pos:"prt"},{jp:"レストラン",en:"restaurant",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきたい",en:"want to go",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 23, level: 3, en: "Ask: Where do you want to go?", jp: "どこに いきたいですか？", romaji: "doko ni ikitai desu ka?",
    words: [{jp:"どこ",en:"where",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきたい",en:"want to go",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 22, level: 3, en: "Say: I don't want to drink alcohol today.", jp: "きょうは おさけを のみたくないです。", romaji: "kyou wa osake o nomitaku nai desu.", hint: "~たい → ~たくない",
    words: [{jp:"きょう",en:"today",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"おさけ",en:"alcohol / sake",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみたくない",en:"don't want to drink",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 325, level: 3, en: "Say: I don't want to go.", jp: "いきたくないです。", romaji: "ikitaku nai desu.",
    words: [{jp:"いきたくない",en:"don't want to go",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 326, level: 3, en: "Say: I didn't want to wake up.", jp: "おきたくなかったです。", romaji: "okitaku nakatta desu.",
    words: [{jp:"おきたくなかった",en:"didn't want to wake up",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 327, level: 3, en: "Say: I want a new phone.", jp: "あたらしい でんわが ほしいです。", romaji: "atarashii denwa ga hoshii desu.", hint: "~が ほしい = want (a thing)",
    words: [{jp:"あたらしい",en:"new",pos:"adj"},{jp:"でんわ",en:"phone",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ほしい",en:"want (a thing)",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 328, level: 3, en: "Say: I don't need presents.", jp: "プレゼントは いりません。", romaji: "purezento wa irimasen.",
    words: [{jp:"プレゼント",en:"presents",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いりません",en:"don't need",pos:"v"}] },
  { id: 4, level: 3, en: "Ask a friend: Shall we go together?", jp: "いっしょに いきましょうか？", romaji: "issho ni ikimashou ka?",
    words: [{jp:"いっしょに",en:"together",pos:"adv"},{jp:"いきましょう",en:"let's go",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 17, level: 3, en: "Say: Let's meet at seven o'clock.", jp: "しちじに あいましょう。", romaji: "shichi-ji ni aimashou.",
    words: [{jp:"しちじ",en:"7 o'clock",pos:"n"},{jp:"に",en:"[at time]",pos:"prt"},{jp:"あいましょう",en:"let's meet",pos:"v"}] },
  { id: 308, level: 3, en: "Say: Let's eat.", jp: "たべましょう。", romaji: "tabemashou.",
    words: [{jp:"たべましょう",en:"let's eat",pos:"v"}] },
  { id: 309, level: 3, en: "Say: Let's go home.", jp: "かえりましょう。", romaji: "kaerimashou.",
    words: [{jp:"かえりましょう",en:"let's go home",pos:"v"}] },
  { id: 310, level: 3, en: "Say: Let's get started.", jp: "はじめましょう。", romaji: "hajimemashou.",
    words: [{jp:"はじめましょう",en:"let's start",pos:"v"}] },
  { id: 312, level: 3, en: "Say: Let's take a break.", jp: "やすみましょう。", romaji: "yasumimashou.",
    words: [{jp:"やすみましょう",en:"let's take a break",pos:"v"}] },
  { id: 313, level: 3, en: "Say: Let's talk in Japanese.", jp: "にほんごで はなしましょう。", romaji: "nihongo de hanashimashou.",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"で",en:"[in/using]",pos:"prt"},{jp:"はなしましょう",en:"let's talk",pos:"v"}] },
  { id: 314, level: 3, en: "Offer help: Shall I help?", jp: "てつだいましょうか？", romaji: "tetsudaimashou ka?",
    words: [{jp:"てつだいましょう",en:"shall I help",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 315, level: 3, en: "Suggest: Shall we take a taxi?", jp: "タクシーに のりましょうか？", romaji: "takushii ni norimashou ka?",
    words: [{jp:"タクシー",en:"taxi",pos:"n"},{jp:"に",en:"[on / into]",pos:"prt"},{jp:"のりましょう",en:"shall we get on",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 20, level: 3, en: "Ask a stranger: Excuse me, do you speak English?", jp: "すみません、えいごが はなせますか？", romaji: "sumimasen, eigo ga hanasemasu ka?", hint: "potential form",
    words: [{jp:"すみません",en:"excuse me",pos:"expr"},{jp:"えいご",en:"English",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"はなせます",en:"can speak",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 316, level: 3, en: "Say: I can speak a little Japanese.", jp: "にほんごが すこし はなせます。", romaji: "nihongo ga sukoshi hanasemasu.",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"すこし",en:"a little",pos:"adv"},{jp:"はなせます",en:"can speak",pos:"v"}] },
  { id: 317, level: 3, en: "Say: I can read hiragana.", jp: "ひらがなが よめます。", romaji: "hiragana ga yomemasu.",
    words: [{jp:"ひらがな",en:"hiragana",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"よめます",en:"can read",pos:"v"}] },
  { id: 318, level: 3, en: "Say: I can't read kanji yet.", jp: "かんじは まだ よめません。", romaji: "kanji wa mada yomemasen.",
    words: [{jp:"かんじ",en:"kanji",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"まだ",en:"yet / still",pos:"adv"},{jp:"よめません",en:"can't read",pos:"v"}] },
  { id: 319, level: 3, en: "Say: I can cook.", jp: "りょうりが できます。", romaji: "ryouri ga dekimasu.",
    words: [{jp:"りょうり",en:"cooking",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"できます",en:"can do",pos:"v"}] },
  { id: 320, level: 3, en: "Ask: Can you swim?", jp: "およげますか？", romaji: "oyogemasu ka?",
    words: [{jp:"およげます",en:"can swim",pos:"v"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 19, level: 3, en: "Say: It was very delicious.", jp: "とても おいしかったです。", romaji: "totemo oishikatta desu.", hint: "i-adj past: ~い → ~かった",
    words: [{jp:"とても",en:"very",pos:"adv"},{jp:"おいしかった",en:"was delicious",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 321, level: 3, en: "Say: The movie was interesting.", jp: "えいがは おもしろかったです。", romaji: "eiga wa omoshirokatta desu.",
    words: [{jp:"えいが",en:"movie",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"おもしろかった",en:"was interesting",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 322, level: 3, en: "Say: The trip was fun.", jp: "りょこうは たのしかったです。", romaji: "ryokou wa tanoshikatta desu.",
    words: [{jp:"りょこう",en:"trip / travel",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"たのしかった",en:"was fun",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 323, level: 3, en: "Say: I wasn't busy yesterday.", jp: "きのうは いそがしくなかったです。", romaji: "kinou wa isogashikunakatta desu.",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いそがしくなかった",en:"wasn't busy",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 324, level: 3, en: "Say: She was kind.", jp: "かのじょは やさしかったです。", romaji: "kanojo wa yasashikatta desu.",
    words: [{jp:"かのじょ",en:"she",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"やさしかった",en:"was kind",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 24, level: 3, en: "Say: My Japanese isn't very good yet.", jp: "にほんごは まだ あまり じょうずじゃ ありません。", romaji: "nihongo wa mada amari jouzu ja arimasen.", hint: "あまり ~ない = not very",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"まだ",en:"yet / still",pos:"adv"},{jp:"あまり",en:"not very (with neg)",pos:"adv"},{jp:"じょうず",en:"good / skilled",pos:"adj"},{jp:"じゃ ありません",en:"is not",pos:"cop"}] },
  { id: 329, level: 3, en: "Say: It's a little far.", jp: "ちょっと とおいです。", romaji: "chotto tooi desu.",
    words: [{jp:"ちょっと",en:"a little",pos:"adv"},{jp:"とおい",en:"far",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 330, level: 3, en: "Say: It's very close.", jp: "とても ちかいです。", romaji: "totemo chikai desu.",
    words: [{jp:"とても",en:"very",pos:"adv"},{jp:"ちかい",en:"close / near",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },

  // ============================================================
  // Level 4 — Intermediate
  // ============================================================
  { id: 410, level: 4, en: "Say: I'm studying Japanese now.", jp: "いま にほんごを べんきょうして います。", romaji: "ima nihongo o benkyou shite imasu.", hint: "~て います = -ing / ongoing",
    words: [{jp:"いま",en:"now",pos:"adv"},{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"べんきょうして",en:"study (te-form)",pos:"v"},{jp:"います",en:"[am ___ing]",pos:"aux"}] },
  { id: 411, level: 4, en: "Say: She's watching TV.", jp: "かのじょは テレビを みて います。", romaji: "kanojo wa terebi o mite imasu.",
    words: [{jp:"かのじょ",en:"she",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"テレビ",en:"TV",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みて",en:"watch (te-form)",pos:"v"},{jp:"います",en:"[is ___ing]",pos:"aux"}] },
  { id: 412, level: 4, en: "Say: He works at a bank.", jp: "かれは ぎんこうで はたらいて います。", romaji: "kare wa ginkou de hataraite imasu.", hint: "~ている also = habitually does",
    words: [{jp:"かれ",en:"he",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ぎんこう",en:"bank",pos:"n"},{jp:"で",en:"[at]",pos:"prt"},{jp:"はたらいて",en:"work (te-form)",pos:"v"},{jp:"います",en:"[habitually]",pos:"aux"}] },
  { id: 413, level: 4, en: "Say: I live in Tokyo.", jp: "とうきょうに すんで います。", romaji: "Toukyou ni sunde imasu.",
    words: [{jp:"とうきょう",en:"Tokyo",pos:"n"},{jp:"に",en:"[in]",pos:"prt"},{jp:"すんで",en:"live (te-form)",pos:"v"},{jp:"います",en:"[state]",pos:"aux"}] },
  { id: 414, level: 4, en: "Say: I know that person.", jp: "あの ひとを しって います。", romaji: "ano hito o shitte imasu.", hint: "know = しっています (not しります)",
    words: [{jp:"あの",en:"that (over there)",pos:"adj"},{jp:"ひと",en:"person",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"しって",en:"know (te-form)",pos:"v"},{jp:"います",en:"[state]",pos:"aux"}] },
  { id: 415, level: 4, en: "Say: I've eaten sushi before.", jp: "おすしを たべた ことが あります。", romaji: "osushi o tabeta koto ga arimasu.", hint: "past plain + ことが あります = have done",
    words: [{jp:"おすし",en:"sushi",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"たべた",en:"ate (plain past)",pos:"v"},{jp:"ことが あります",en:"have the experience of",pos:"expr"}] },
  { id: 416, level: 4, en: "Say: I've never been to Kyoto.", jp: "きょうとに いった ことが ありません。", romaji: "Kyouto ni itta koto ga arimasen.",
    words: [{jp:"きょうと",en:"Kyoto",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いった",en:"went (plain past)",pos:"v"},{jp:"ことが ありません",en:"have never (done)",pos:"expr"}] },
  { id: 417, level: 4, en: "Say: I've heard that song before.", jp: "その うたを きいた ことが あります。", romaji: "sono uta o kiita koto ga arimasu.",
    words: [{jp:"その",en:"that",pos:"adj"},{jp:"うた",en:"song",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"きいた",en:"heard (plain past)",pos:"v"},{jp:"ことが あります",en:"have done before",pos:"expr"}] },
  { id: 13, level: 4, en: "Say: I have to work tomorrow.", jp: "あした はたらかなければ なりません。", romaji: "ashita hatarakanakereba narimasen.", hint: "~なければ なりません = must",
    words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"はたらかなければ なりません",en:"must work",pos:"v"}] },
  { id: 418, level: 4, en: "Say: I have to study tonight.", jp: "こんばん べんきょうしなければ なりません。", romaji: "konban benkyou shinakereba narimasen.",
    words: [{jp:"こんばん",en:"tonight",pos:"n"},{jp:"べんきょうしなければ なりません",en:"must study",pos:"v"}] },
  { id: 419, level: 4, en: "Say: I have to wake up early tomorrow.", jp: "あした はやく おきなければ なりません。", romaji: "ashita hayaku okinakereba narimasen.",
    words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"はやく",en:"early",pos:"adv"},{jp:"おきなければ なりません",en:"must wake up",pos:"v"}] },
  { id: 420, level: 4, en: "Say: You don't have to apologize.", jp: "あやまらなくても いいです。", romaji: "ayamaranakute mo ii desu.", hint: "~なくても いい = don't have to",
    words: [{jp:"あやまらなくても",en:"even if (you) don't apologize",pos:"v"},{jp:"いい",en:"OK / fine",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 421, level: 4, en: "Ask: May I sit here?", jp: "ここに すわっても いいですか？", romaji: "koko ni suwatte mo ii desu ka?", hint: "~ても いい = may ___",
    words: [{jp:"ここ",en:"here",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"すわって",en:"sit (te-form)",pos:"v"},{jp:"も",en:"[even]",pos:"prt"},{jp:"いい",en:"OK",pos:"adj"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 422, level: 4, en: "Ask: May I use this?", jp: "これを つかっても いいですか？", romaji: "kore o tsukatte mo ii desu ka?",
    words: [{jp:"これ",en:"this",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"つかって",en:"use (te-form)",pos:"v"},{jp:"も",en:"[even]",pos:"prt"},{jp:"いい",en:"OK",pos:"adj"},{jp:"です",en:"is",pos:"cop"},{jp:"か",en:"[?]",pos:"prt"}] },
  { id: 423, level: 4, en: "Say: You must not smoke here.", jp: "ここで たばこを すっては いけません。", romaji: "koko de tabako o sutte wa ikemasen.", hint: "~ては いけません = must not",
    words: [{jp:"ここ",en:"here",pos:"n"},{jp:"で",en:"[at]",pos:"prt"},{jp:"たばこ",en:"cigarette",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"すっては いけません",en:"must not smoke",pos:"v"}] },
  { id: 424, level: 4, en: "Say: I think this is correct.", jp: "これは ただしいと おもいます。", romaji: "kore wa tadashii to omoimasu.", hint: "plain + と おもいます = I think",
    words: [{jp:"これ",en:"this",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ただしい",en:"correct",pos:"adj"},{jp:"と",en:"[that—quote]",pos:"prt"},{jp:"おもいます",en:"think",pos:"v"}] },
  { id: 425, level: 4, en: "Say: I think she's coming.", jp: "かのじょは くると おもいます。", romaji: "kanojo wa kuru to omoimasu.",
    words: [{jp:"かのじょ",en:"she",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"くる",en:"come (plain)",pos:"v"},{jp:"と",en:"[that—quote]",pos:"prt"},{jp:"おもいます",en:"think",pos:"v"}] },
  { id: 426, level: 4, en: "Say: He said he was tired.", jp: "かれは つかれたと いいました。", romaji: "kare wa tsukareta to iimashita.", hint: "plain + と いいました = said",
    words: [{jp:"かれ",en:"he",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"つかれた",en:"got tired (plain past)",pos:"v"},{jp:"と",en:"[that—quote]",pos:"prt"},{jp:"いいました",en:"said",pos:"v"}] },
  { id: 427, level: 4, en: "Say: I'm better at English than Japanese.", jp: "にほんごより えいごの ほうが じょうずです。", romaji: "nihongo yori eigo no hou ga jouzu desu.", hint: "より = than; ほう = side",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"より",en:"than",pos:"prt"},{jp:"えいご",en:"English",pos:"n"},{jp:"の",en:"[of]",pos:"prt"},{jp:"ほう",en:"side / one",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"じょうず",en:"skilled / good at",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 428, level: 4, en: "Say: Sushi is more delicious than ramen.", jp: "ラーメンより おすしの ほうが おいしいです。", romaji: "raamen yori osushi no hou ga oishii desu.",
    words: [{jp:"ラーメン",en:"ramen",pos:"n"},{jp:"より",en:"than",pos:"prt"},{jp:"おすし",en:"sushi",pos:"n"},{jp:"の",en:"[of]",pos:"prt"},{jp:"ほう",en:"side / one",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"おいしい",en:"delicious",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 429, level: 4, en: "Say: I'm good at cooking.", jp: "りょうりが じょうずです。", romaji: "ryouri ga jouzu desu.",
    words: [{jp:"りょうり",en:"cooking",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"じょうず",en:"good at",pos:"adj"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 430, level: 4, en: "Say: I'm bad at math.", jp: "すうがくが にがてです。", romaji: "suugaku ga nigate desu.",
    words: [{jp:"すうがく",en:"math",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"にがて",en:"weak at / bad at",pos:"adj"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 431, level: 4, en: "Say: I like reading books.", jp: "ほんを よむのが すきです。", romaji: "hon o yomu no ga suki desu.", hint: "verb plain + の = the act of ___ing",
    words: [{jp:"ほん",en:"book",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"よむ",en:"read (plain)",pos:"v"},{jp:"の",en:"[nominalizer—the act of]",pos:"prt"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"すき",en:"liked / fond of",pos:"adj"},{jp:"です",en:"am",pos:"cop"}] },
  { id: 432, level: 4, en: "Say: I sometimes go to the gym.", jp: "ときどき ジムに いきます。", romaji: "tokidoki jimu ni ikimasu.",
    words: [{jp:"ときどき",en:"sometimes",pos:"adv"},{jp:"ジム",en:"gym",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきます",en:"go",pos:"v"}] },
  { id: 433, level: 4, en: "Say: I usually have coffee in the morning.", jp: "たいてい あさ コーヒーを のみます。", romaji: "taitei asa koohii o nomimasu.",
    words: [{jp:"たいてい",en:"usually",pos:"adv"},{jp:"あさ",en:"morning",pos:"n"},{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみます",en:"drink",pos:"v"}] },
  { id: 434, level: 4, en: "Say: I work while listening to music.", jp: "おんがくを ききながら しごとを します。", romaji: "ongaku o kikinagara shigoto o shimasu.", hint: "~ながら = while ___ing",
    words: [{jp:"おんがく",en:"music",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"きき",en:"listen (stem)",pos:"v"},{jp:"ながら",en:"while ___ing",pos:"aux"},{jp:"しごと",en:"work",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"します",en:"do",pos:"v"}] },

  // ============================================================
  // Level 5 — Conversational
  // ============================================================
  { id: 510, level: 5, en: "Say: I can't go because I'm busy.", jp: "いそがしいから、いけません。", romaji: "isogashii kara, ikemasen.", hint: "~から = because (reason first)",
    words: [{jp:"いそがしい",en:"busy",pos:"adj"},{jp:"から",en:"because",pos:"conj"},{jp:"いけません",en:"can't go",pos:"v"}] },
  { id: 501, level: 5, en: "Say: Because it was raining, I didn't go out.", jp: "あめが ふって いたから、でかけませんでした。", romaji: "ame ga futte ita kara, dekakemasen deshita.",
    words: [{jp:"あめ",en:"rain",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ふって いた",en:"was falling",pos:"v"},{jp:"から",en:"because",pos:"conj"},{jp:"でかけませんでした",en:"didn't go out",pos:"v"}] },
  { id: 511, level: 5, en: "Say: I went home because it got cold.", jp: "さむく なったから、かえりました。", romaji: "samuku natta kara, kaerimashita.", hint: "なる = become",
    words: [{jp:"さむく",en:"cold (adv)",pos:"adj"},{jp:"なった",en:"became",pos:"v"},{jp:"から",en:"because",pos:"conj"},{jp:"かえりました",en:"went home",pos:"v"}] },
  { id: 502, level: 5, en: "Say: If you have time, let's get coffee.", jp: "じかんが あれば、コーヒーを のみましょう。", romaji: "jikan ga areba, koohii o nomimashou.", hint: "~ば = if",
    words: [{jp:"じかん",en:"time",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"あれば",en:"if there is",pos:"v"},{jp:"コーヒー",en:"coffee",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"のみましょう",en:"let's drink",pos:"v"}] },
  { id: 513, level: 5, en: "Say: If it's sunny tomorrow, let's go to the park.", jp: "あした はれたら、こうえんに いきましょう。", romaji: "ashita haretara, kouen ni ikimashou.", hint: "~たら = if/when",
    words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"はれたら",en:"if it clears up",pos:"v"},{jp:"こうえん",en:"park",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いきましょう",en:"let's go",pos:"v"}] },
  { id: 512, level: 5, en: "Say: If you eat too much, you'll gain weight.", jp: "たべすぎると ふとりますよ。", romaji: "tabesugiru to futorimasu yo.", hint: "~と = whenever/if (natural consequence)",
    words: [{jp:"たべすぎる",en:"eat too much (plain)",pos:"v"},{jp:"と",en:"if / whenever",pos:"conj"},{jp:"ふとります",en:"gain weight",pos:"v"},{jp:"よ",en:"[emphasis!]",pos:"prt"}] },
  { id: 503, level: 5, en: "Say: When I was a child, I lived in Osaka.", jp: "こどもの とき、おおさかに すんで いました。", romaji: "kodomo no toki, oosaka ni sunde imashita.", hint: "~の とき = when (was) ___",
    words: [{jp:"こども",en:"child",pos:"n"},{jp:"の",en:"[of]",pos:"prt"},{jp:"とき",en:"time / when",pos:"n"},{jp:"おおさか",en:"Osaka",pos:"n"},{jp:"に",en:"[in]",pos:"prt"},{jp:"すんで いました",en:"was living",pos:"v"}] },
  { id: 514, level: 5, en: "Say: When I was a student, I studied a lot.", jp: "がくせいの とき、よく べんきょうしました。", romaji: "gakusei no toki, yoku benkyou shimashita.",
    words: [{jp:"がくせい",en:"student",pos:"n"},{jp:"の",en:"[of]",pos:"prt"},{jp:"とき",en:"time / when",pos:"n"},{jp:"よく",en:"a lot / often",pos:"adv"},{jp:"べんきょうしました",en:"studied",pos:"v"}] },
  { id: 515, level: 5, en: "Say: Before going to bed, I brush my teeth.", jp: "ねる まえに、はを みがきます。", romaji: "neru mae ni, ha o migakimasu.", hint: "plain + まえに = before ___ing",
    words: [{jp:"ねる",en:"sleep (plain)",pos:"v"},{jp:"まえに",en:"before",pos:"conj"},{jp:"は",en:"teeth (歯)",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みがきます",en:"brush / polish",pos:"v"}] },
  { id: 516, level: 5, en: "Say: After eating, let's go for a walk.", jp: "たべた あとで、さんぽしましょう。", romaji: "tabeta ato de, sanpo shimashou.", hint: "past plain + あとで = after ___ing",
    words: [{jp:"たべた",en:"ate (plain past)",pos:"v"},{jp:"あとで",en:"after",pos:"conj"},{jp:"さんぽしましょう",en:"let's take a walk",pos:"v"}] },
  { id: 505, level: 5, en: "Say: After I finish work, I'll go home.", jp: "しごとが おわってから、うちに かえります。", romaji: "shigoto ga owatte kara, uchi ni kaerimasu.", hint: "~てから = after ___ing",
    words: [{jp:"しごと",en:"work",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"おわって",en:"finish (te-form)",pos:"v"},{jp:"から",en:"after",pos:"conj"},{jp:"うち",en:"home",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"かえります",en:"go home",pos:"v"}] },
  { id: 504, level: 5, en: "Say: Even if it's expensive, I want to buy it.", jp: "たかくても、かいたいです。", romaji: "takakute mo, kaitai desu.", hint: "~ても = even if",
    words: [{jp:"たかくても",en:"even if expensive",pos:"adj"},{jp:"かいたい",en:"want to buy",pos:"v"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 517, level: 5, en: "Say: Even if it rains, I'll go.", jp: "あめが ふっても、いきます。", romaji: "ame ga futte mo, ikimasu.",
    words: [{jp:"あめ",en:"rain",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ふっても",en:"even if it falls",pos:"v"},{jp:"いきます",en:"will go",pos:"v"}] },
  { id: 506, level: 5, en: "Say: I haven't decided what to do yet.", jp: "なにを するか まだ きめて いません。", romaji: "nani o suru ka mada kimete imasen.", hint: "embedded question with か",
    words: [{jp:"なに",en:"what",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"する",en:"do (plain)",pos:"v"},{jp:"か",en:"[whether—embedded?]",pos:"prt"},{jp:"まだ",en:"yet",pos:"adv"},{jp:"きめて",en:"decide (te-form)",pos:"v"},{jp:"いません",en:"[haven't ___ed]",pos:"aux"}] },
  { id: 518, level: 5, en: "Say: I don't know what to do.", jp: "なにを すれば いいか わかりません。", romaji: "nani o sureba ii ka wakarimasen.",
    words: [{jp:"なに",en:"what",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"すれば",en:"if (I) do",pos:"v"},{jp:"いい",en:"good / right",pos:"adj"},{jp:"か",en:"[whether]",pos:"prt"},{jp:"わかりません",en:"don't know",pos:"v"}] },
  { id: 519, level: 5, en: "Say: I forgot where I parked.", jp: "どこに とめたか わすれました。", romaji: "doko ni tometa ka wasuremashita.",
    words: [{jp:"どこ",en:"where",pos:"n"},{jp:"に",en:"[at]",pos:"prt"},{jp:"とめた",en:"parked (plain past)",pos:"v"},{jp:"か",en:"[whether]",pos:"prt"},{jp:"わすれました",en:"forgot",pos:"v"}] },
  { id: 508, level: 5, en: "Say: The restaurant I went to yesterday was really good.", jp: "きのう いった レストランは とても よかったです。", romaji: "kinou itta resutoran wa totemo yokatta desu.", hint: "plain past modifies noun (relative clause)",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"いった",en:"went (modifies →)",pos:"v"},{jp:"レストラン",en:"restaurant",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"とても",en:"very",pos:"adv"},{jp:"よかった",en:"was good",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 520, level: 5, en: "Say: The person I met yesterday was kind.", jp: "きのう あった ひとは やさしかったです。", romaji: "kinou atta hito wa yasashikatta desu.",
    words: [{jp:"きのう",en:"yesterday",pos:"n"},{jp:"あった",en:"met (modifies →)",pos:"v"},{jp:"ひと",en:"person",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"やさしかった",en:"was kind",pos:"adj"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 521, level: 5, en: "Say: The food my mom makes is the best.", jp: "ははが つくる りょうりが いちばん おいしいです。", romaji: "haha ga tsukuru ryouri ga ichiban oishii desu.",
    words: [{jp:"はは",en:"mom",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"つくる",en:"makes (modifies →)",pos:"v"},{jp:"りょうり",en:"cooking / food",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"いちばん",en:"the most / #1",pos:"adv"},{jp:"おいしい",en:"delicious",pos:"adj"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 524, level: 5, en: "Say: It looks delicious.", jp: "おいしそうです。", romaji: "oishisou desu.", hint: "i-adj stem + そう = looks ___",
    words: [{jp:"おいし",en:"delicious (stem)",pos:"adj"},{jp:"そう",en:"looks / seems",pos:"aux"},{jp:"です",en:"is",pos:"cop"}] },
  { id: 525, level: 5, en: "Say: It looks like it's going to rain.", jp: "あめが ふりそうです。", romaji: "ame ga furisou desu.", hint: "verb stem + そう = looks like",
    words: [{jp:"あめ",en:"rain",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ふり",en:"fall (stem)",pos:"v"},{jp:"そう",en:"looks like / about to",pos:"aux"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 526, level: 5, en: "Say: She seems busy.", jp: "かのじょは いそがしい みたいです。", romaji: "kanojo wa isogashii mitai desu.", hint: "~みたい = seems / looks like",
    words: [{jp:"かのじょ",en:"she",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"いそがしい",en:"busy",pos:"adj"},{jp:"みたい",en:"seems / looks like",pos:"aux"},{jp:"です",en:"[polite]",pos:"cop"}] },
  { id: 527, level: 5, en: "Say: It might rain tomorrow.", jp: "あした あめが ふるかも しれません。", romaji: "ashita ame ga furu kamo shiremasen.", hint: "~かもしれません = might",
    words: [{jp:"あした",en:"tomorrow",pos:"n"},{jp:"あめ",en:"rain",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"ふる",en:"fall (plain)",pos:"v"},{jp:"かも しれません",en:"might / maybe",pos:"aux"}] },
  { id: 528, level: 5, en: "Say: He might come.", jp: "かれは くるかも しれません。", romaji: "kare wa kuru kamo shiremasen.",
    words: [{jp:"かれ",en:"he",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"くる",en:"come (plain)",pos:"v"},{jp:"かも しれません",en:"might / maybe",pos:"aux"}] },
  { id: 529, level: 5, en: "Say: I've come to understand Japanese.", jp: "にほんごが わかるように なりました。", romaji: "nihongo ga wakaru you ni narimashita.", hint: "~ように なる = come to ___",
    words: [{jp:"にほんご",en:"Japanese",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"わかる",en:"understand (plain)",pos:"v"},{jp:"ように",en:"to the point of",pos:"conj"},{jp:"なりました",en:"became / came to",pos:"v"}] },
  { id: 530, level: 5, en: "Say: I can read kanji now (didn't used to).", jp: "かんじが よめるように なりました。", romaji: "kanji ga yomeru you ni narimashita.",
    words: [{jp:"かんじ",en:"kanji",pos:"n"},{jp:"が",en:"[subject]",pos:"prt"},{jp:"よめる",en:"can read (plain)",pos:"v"},{jp:"ように",en:"to the point of",pos:"conj"},{jp:"なりました",en:"became",pos:"v"}] },
  { id: 532, level: 5, en: "Say: On weekends I read and watch movies (among other things).", jp: "しゅうまつは ほんを よんだり、えいがを みたり します。", romaji: "shuumatsu wa hon o yondari, eiga o mitari shimasu.", hint: "~たり ~たり する = do A and B (non-exhaustive)",
    words: [{jp:"しゅうまつ",en:"weekend",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"ほん",en:"book",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"よんだり",en:"read (among other things)",pos:"v"},{jp:"えいが",en:"movie",pos:"n"},{jp:"を",en:"[object]",pos:"prt"},{jp:"みたり",en:"watch (among other things)",pos:"v"},{jp:"します",en:"do",pos:"v"}] },
  { id: 533, level: 5, en: "Say: It's gradually getting colder.", jp: "だんだん さむく なって きました。", romaji: "dandan samuku natte kimashita.", hint: "~なってくる = becoming over time",
    words: [{jp:"だんだん",en:"gradually",pos:"adv"},{jp:"さむく",en:"cold (adv)",pos:"adj"},{jp:"なって",en:"become (te-form)",pos:"v"},{jp:"きました",en:"[has come to be]",pos:"aux"}] },
  { id: 534, level: 5, en: "Say: I'm thinking of going to Japan.", jp: "にほんに いこうと おもって います。", romaji: "nihon ni ikou to omotte imasu.", hint: "volitional + と おもって います",
    words: [{jp:"にほん",en:"Japan",pos:"n"},{jp:"に",en:"[to]",pos:"prt"},{jp:"いこう",en:"let's go (volitional)",pos:"v"},{jp:"と",en:"[that—quote]",pos:"prt"},{jp:"おもって",en:"think (te-form)",pos:"v"},{jp:"います",en:"[ongoing]",pos:"aux"}] },
  { id: 522, level: 5, en: "Say casually: I'm gonna head out.", jp: "もう いくよ。", romaji: "mou iku yo.", hint: "plain form + よ (casual)",
    words: [{jp:"もう",en:"already / now",pos:"adv"},{jp:"いく",en:"go (plain)",pos:"v"},{jp:"よ",en:"[!—telling you]",pos:"prt"}] },
  { id: 507, level: 5, en: "Say casually: I'm going to bed — I'm sleepy.", jp: "ねむいから もう ねるよ。", romaji: "nemui kara mou neru yo.",
    words: [{jp:"ねむい",en:"sleepy",pos:"adj"},{jp:"から",en:"because",pos:"conj"},{jp:"もう",en:"already / now",pos:"adv"},{jp:"ねる",en:"sleep (plain)",pos:"v"},{jp:"よ",en:"[!]",pos:"prt"}] },
  { id: 531, level: 5, en: "Say (reporting): She said she'd come.", jp: "かのじょは くるって いって いました。", romaji: "kanojo wa kuru tte itte imashita.", hint: "って = casual quote",
    words: [{jp:"かのじょ",en:"she",pos:"n"},{jp:"は",en:"[topic]",pos:"prt"},{jp:"くる",en:"come (plain)",pos:"v"},{jp:"って",en:"[casual quote]",pos:"prt"},{jp:"いって",en:"say (te-form)",pos:"v"},{jp:"いました",en:"[was ___ing]",pos:"aux"}] },
];
