// Prompt & Respond drills.
// Aiming roughly at Pimsleur level 4-5: past tense, ~たい (want to),
// ~ましょう (let's), basic adjectives, time, directions, polite requests.
// Edit/add freely — each prompt needs en (situation), jp (kana answer), and romaji.

window.PROMPTS = [
  {
    id: 1,
    en: "Ask what time it is now.",
    jp: "いま なんじですか？",
    romaji: "ima nanji desu ka?",
    hint: "いま = now",
    tags: ["time", "question"],
  },
  {
    id: 2,
    en: "Say: I want to drink coffee.",
    jp: "コーヒーが のみたいです。",
    romaji: "koohii ga nomitai desu.",
    hint: "verb-stem + たい = want to ___",
    tags: ["tai", "food"],
  },
  {
    id: 3,
    en: "Say: I would like to eat sushi.",
    jp: "おすしが たべたいです。",
    romaji: "osushi ga tabetai desu.",
    hint: "たべる → たべたい",
    tags: ["tai", "food"],
  },
  {
    id: 4,
    en: "Ask a friend: Shall we go together?",
    jp: "いっしょに いきましょうか？",
    romaji: "issho ni ikimashou ka?",
    hint: "~ましょうか = shall we ___?",
    tags: ["mashou", "invite"],
  },
  {
    id: 5,
    en: "Say: I ate breakfast this morning.",
    jp: "けさ あさごはんを たべました。",
    romaji: "kesa asagohan o tabemashita.",
    hint: "けさ = this morning; past polite = ~ました",
    tags: ["past", "food"],
  },
  {
    id: 6,
    en: "Ask: Where is the station?",
    jp: "えきは どこですか？",
    romaji: "eki wa doko desu ka?",
    hint: "どこ = where",
    tags: ["directions", "question"],
  },
  {
    id: 7,
    en: "Say: It's a little expensive.",
    jp: "ちょっと たかいです。",
    romaji: "chotto takai desu.",
    hint: "ちょっと = a little",
    tags: ["adjective"],
  },
  {
    id: 8,
    en: "Politely ask: Could you say it one more time?",
    jp: "もういちど いって ください。",
    romaji: "mou ichido itte kudasai.",
    hint: "もういちど = one more time; ~て ください = please ___",
    tags: ["request", "te-form"],
  },
  {
    id: 9,
    en: "Say: I went to Tokyo yesterday.",
    jp: "きのう とうきょうに いきました。",
    romaji: "kinou Toukyou ni ikimashita.",
    hint: "に marks destination",
    tags: ["past", "travel"],
  },
  {
    id: 10,
    en: "Say: I don't understand Japanese well.",
    jp: "にほんごが よく わかりません。",
    romaji: "nihongo ga yoku wakarimasen.",
    hint: "よく = well; わかりません = don't understand",
    tags: ["negative"],
  },
  {
    id: 11,
    en: "Ask: How much is this?",
    jp: "これは いくらですか？",
    romaji: "kore wa ikura desu ka?",
    hint: "いくら = how much",
    tags: ["shopping", "question"],
  },
  {
    id: 12,
    en: "Say: I'd like to go to a Japanese restaurant tonight.",
    jp: "こんばん にほんりょうりの レストランに いきたいです。",
    romaji: "konban nihonryouri no resutoran ni ikitai desu.",
    hint: "こんばん = tonight; の links nouns",
    tags: ["tai", "food"],
  },
  {
    id: 13,
    en: "Say: I have to work tomorrow.",
    jp: "あした はたらかなければ なりません。",
    romaji: "ashita hatarakanakereba narimasen.",
    hint: "~なければ なりません = must ___",
    tags: ["obligation"],
  },
  {
    id: 14,
    en: "Ask: Do you have time now?",
    jp: "いま じかんが ありますか？",
    romaji: "ima jikan ga arimasu ka?",
    hint: "じかん = time; あります = have/exists",
    tags: ["question"],
  },
  {
    id: 15,
    en: "Say: My wife is at home.",
    jp: "つまは うちに います。",
    romaji: "tsuma wa uchi ni imasu.",
    hint: "います for people; あります for things",
    tags: ["family", "location"],
  },
  {
    id: 16,
    en: "Politely decline: No thank you, I'm fine.",
    jp: "いいえ、けっこうです。",
    romaji: "iie, kekkou desu.",
    hint: "けっこうです = that's enough / I'm good",
    tags: ["politeness"],
  },
  {
    id: 17,
    en: "Say: Let's meet at seven o'clock.",
    jp: "しちじに あいましょう。",
    romaji: "shichi-ji ni aimashou.",
    hint: "に attaches to a specific time",
    tags: ["mashou", "time"],
  },
  {
    id: 18,
    en: "Ask: What did you do yesterday?",
    jp: "きのう なにを しましたか？",
    romaji: "kinou nani o shimashita ka?",
    hint: "しました = did",
    tags: ["past", "question"],
  },
  {
    id: 19,
    en: "Say: It was very delicious.",
    jp: "とても おいしかったです。",
    romaji: "totemo oishikatta desu.",
    hint: "i-adj past: ~い → ~かった",
    tags: ["past", "adjective"],
  },
  {
    id: 20,
    en: "Ask a stranger: Excuse me, do you speak English?",
    jp: "すみません、えいごが はなせますか？",
    romaji: "sumimasen, eigo ga hanasemasu ka?",
    hint: "はなせます = can speak",
    tags: ["potential", "question"],
  },
  {
    id: 21,
    en: "Say: I will probably go tomorrow.",
    jp: "あした たぶん いきます。",
    romaji: "ashita tabun ikimasu.",
    hint: "たぶん = probably",
    tags: ["future"],
  },
  {
    id: 22,
    en: "Say: I don't want to drink alcohol today.",
    jp: "きょうは おさけを のみたく ないです。",
    romaji: "kyou wa osake o nomitaku nai desu.",
    hint: "~たい → ~たくない (don't want to)",
    tags: ["tai", "negative"],
  },
  {
    id: 23,
    en: "Ask: Where do you want to go?",
    jp: "どこに いきたいですか？",
    romaji: "doko ni ikitai desu ka?",
    hint: "combine どこ + いきたい",
    tags: ["tai", "question"],
  },
  {
    id: 24,
    en: "Say: My Japanese isn't very good yet.",
    jp: "にほんごは まだ あまり じょうずじゃ ありません。",
    romaji: "nihongo wa mada amari jouzu ja arimasen.",
    hint: "まだ = still/yet; あまり ~ない = not very",
    tags: ["negative", "adjective"],
  },
  {
    id: 25,
    en: "Politely ask: Could you speak a little more slowly?",
    jp: "もうすこし ゆっくり はなして ください。",
    romaji: "mou sukoshi yukkuri hanashite kudasai.",
    hint: "もうすこし = a little more; ゆっくり = slowly",
    tags: ["request", "te-form"],
  },
];
