// Prompt & Respond drills — conversational Japanese.
// Each prompt: { id, level (1-5), en, jp, romaji, hint?, tags? }
//
// Level scheme:
//   1 — Survival:       greetings, fixed phrases, basic です questions
//   2 — Daily polite:   ~ます / ~ました / ~ません, て-form requests, daily routine
//   3 — Pimsleur 4-5:   ~たい, ~ましょう, adjective past, potential, ~ほしい
//   4 — Intermediate:   ~ている, ~たことがある, must/can/let, comparison, ~と思う
//   5 — Conversational: from/because/when/if/even-if, relative clauses,
//                       embedded questions, plain form, ~みたい/~そう/~かも

window.PROMPTS = [
  // ============================================================
  // Level 1 — Survival (fixed phrases + bare-bones questions)
  // ============================================================
  { id: 101, level: 1, en: "Greet someone in the morning.",                jp: "おはよう ございます。",        romaji: "ohayou gozaimasu.",       hint: "polite morning greeting" },
  { id: 110, level: 1, en: "Greet someone in the daytime.",                jp: "こんにちは。",                  romaji: "konnichiwa.",             hint: "general 'hello'" },
  { id: 111, level: 1, en: "Greet someone in the evening.",                jp: "こんばんは。",                  romaji: "konbanwa.",               hint: "evening greeting" },
  { id: 112, level: 1, en: "Say good night.",                              jp: "おやすみなさい。",              romaji: "oyasumi nasai." },
  { id: 113, level: 1, en: "Say goodbye (formal).",                        jp: "さようなら。",                  romaji: "sayounara." },
  { id: 114, level: 1, en: "Say: See you tomorrow.",                       jp: "また あした。",                 romaji: "mata ashita." },
  { id: 102, level: 1, en: "Say: Nice to meet you.",                       jp: "はじめまして。",                romaji: "hajimemashite.",          hint: "used on first meeting" },
  { id: 103, level: 1, en: "Say thank you (politely).",                    jp: "ありがとう ございます。",       romaji: "arigatou gozaimasu." },
  { id: 104, level: 1, en: "Say: Excuse me / I'm sorry.",                  jp: "すみません。",                  romaji: "sumimasen.",              hint: "all-purpose excuse me" },
  { id: 141, level: 1, en: "Apologize sincerely.",                         jp: "ごめんなさい。",                romaji: "gomen nasai." },
  { id: 115, level: 1, en: "Say yes.",                                     jp: "はい。",                        romaji: "hai." },
  { id: 116, level: 1, en: "Say no.",                                      jp: "いいえ。",                      romaji: "iie." },
  { id: 105, level: 1, en: "Say: I am American.",                          jp: "わたしは アメリカじんです。",   romaji: "watashi wa amerika-jin desu.", hint: "~じん = ___-person" },
  { id: 117, level: 1, en: "Say: My name is Tom.",                         jp: "わたしは トムです。",           romaji: "watashi wa Tomu desu." },
  { id: 135, level: 1, en: "Ask: What's your name?",                       jp: "おなまえは なんですか？",       romaji: "onamae wa nan desu ka?" },
  { id: 118, level: 1, en: "Say: I'm a student.",                          jp: "がくせいです。",                romaji: "gakusei desu." },
  { id: 119, level: 1, en: "Say: I'm thirty-five years old.",              jp: "さんじゅうごさいです。",        romaji: "sanjuugo-sai desu." },
  { id: 133, level: 1, en: "Ask: How are you?",                            jp: "おげんきですか？",              romaji: "ogenki desu ka?" },
  { id: 132, level: 1, en: "Reply: I'm fine, thanks.",                     jp: "げんきです。",                  romaji: "genki desu." },
  { id: 1,   level: 1, en: "Ask what time it is now.",                     jp: "いま なんじですか？",           romaji: "ima nanji desu ka?",      hint: "いま = now" },
  { id: 6,   level: 1, en: "Ask: Where is the station?",                   jp: "えきは どこですか？",           romaji: "eki wa doko desu ka?" },
  { id: 134, level: 1, en: "Ask: Where is the bathroom?",                  jp: "トイレは どこですか？",         romaji: "toire wa doko desu ka?" },
  { id: 11,  level: 1, en: "Ask: How much is this?",                       jp: "これは いくらですか？",         romaji: "kore wa ikura desu ka?" },
  { id: 106, level: 1, en: "Ask: What is this?",                           jp: "これは なんですか？",           romaji: "kore wa nan desu ka?" },
  { id: 16,  level: 1, en: "Politely decline: No thank you, I'm fine.",    jp: "いいえ、けっこうです。",         romaji: "iie, kekkou desu." },
  { id: 121, level: 1, en: "Say: Please (when requesting something).",     jp: "おねがいします。",              romaji: "onegai shimasu." },
  { id: 126, level: 1, en: "Order: A menu, please.",                       jp: "メニューを おねがいします。",   romaji: "menyuu o onegai shimasu." },
  { id: 127, level: 1, en: "Order: One beer, please.",                     jp: "ビールを ひとつ おねがいします。", romaji: "biiru o hitotsu onegai shimasu." },
  { id: 128, level: 1, en: "Ask for the bill.",                            jp: "おかいけい おねがいします。",   romaji: "okaikei onegai shimasu." },
  { id: 129, level: 1, en: "Say: It's delicious.",                         jp: "おいしいです。",                romaji: "oishii desu." },
  { id: 130, level: 1, en: "Say: It's hot today.",                         jp: "きょうは あついです。",         romaji: "kyou wa atsui desu." },
  { id: 131, level: 1, en: "Say: It's cold today.",                        jp: "きょうは さむいです。",         romaji: "kyou wa samui desu." },
  { id: 124, level: 1, en: "Say: I don't understand.",                     jp: "わかりません。",                romaji: "wakarimasen." },
  { id: 140, level: 1, en: "Say: Got it / I understand.",                  jp: "わかりました。",                romaji: "wakarimashita." },
  { id: 125, level: 1, en: "Ask: One more time, please.",                  jp: "もういちど おねがいします。",   romaji: "mou ichido onegai shimasu." },
  { id: 142, level: 1, en: "Say: Just a moment, please.",                  jp: "ちょっと まって ください。",    romaji: "chotto matte kudasai." },
  { id: 149, level: 1, en: "Say: It's OK / no problem.",                   jp: "だいじょうぶです。",            romaji: "daijoubu desu." },
  { id: 137, level: 1, en: "Confirm: That's right.",                       jp: "そうです。",                    romaji: "sou desu." },
  { id: 145, level: 1, en: "React positively: That sounds good.",          jp: "いいですね。",                  romaji: "ii desu ne." },
  { id: 146, level: 1, en: "React: Really?",                               jp: "ほんとうですか？",              romaji: "hontou desu ka?" },
  { id: 147, level: 1, en: "React: I see / oh I get it.",                  jp: "なるほど。",                    romaji: "naruhodo." },
  { id: 143, level: 1, en: "Toast: Cheers!",                               jp: "かんぱい！",                    romaji: "kanpai!" },
  { id: 144, level: 1, en: "Say: Thanks for your hard work. (leaving work)", jp: "おつかれさまでした。",        romaji: "otsukaresama deshita." },

  // ============================================================
  // Level 2 — Daily polite (~ます forms, routine, basic requests)
  // ============================================================
  { id: 201, level: 2, en: "Say: I wake up at seven.",                     jp: "しちじに おきます。",           romaji: "shichi-ji ni okimasu." },
  { id: 202, level: 2, en: "Say: I go to work by train.",                  jp: "でんしゃで しごとに いきます。", romaji: "densha de shigoto ni ikimasu.", hint: "で = by means of" },
  { id: 203, level: 2, en: "Say: I eat lunch at noon.",                    jp: "じゅうにじに おひるごはんを たべます。", romaji: "juuni-ji ni ohirugohan o tabemasu." },
  { id: 204, level: 2, en: "Say: I come home at seven.",                   jp: "しちじに うちに かえります。",  romaji: "shichi-ji ni uchi ni kaerimasu." },
  { id: 205, level: 2, en: "Say: I go to bed at eleven.",                  jp: "じゅういちじに ねます。",       romaji: "juuichi-ji ni nemasu." },
  { id: 206, level: 2, en: "Say: I drink coffee every morning.",           jp: "まいあさ コーヒーを のみます。", romaji: "maiasa koohii o nomimasu." },
  { id: 207, level: 2, en: "Say: I read books on weekends.",               jp: "しゅうまつに ほんを よみます。", romaji: "shuumatsu ni hon o yomimasu." },
  { id: 5,   level: 2, en: "Say: I ate breakfast this morning.",           jp: "けさ あさごはんを たべました。", romaji: "kesa asagohan o tabemashita." },
  { id: 208, level: 2, en: "Say: I watched a movie yesterday.",            jp: "きのう えいがを みました。",    romaji: "kinou eiga o mimashita." },
  { id: 209, level: 2, en: "Say: I bought new shoes.",                     jp: "あたらしい くつを かいました。", romaji: "atarashii kutsu o kaimashita." },
  { id: 210, level: 2, en: "Say: I met a friend yesterday.",               jp: "きのう ともだちに あいました。", romaji: "kinou tomodachi ni aimashita.", hint: "に person + あう = meet ___" },
  { id: 211, level: 2, en: "Say: I called my mother.",                     jp: "ははに でんわしました。",       romaji: "haha ni denwa shimashita." },
  { id: 212, level: 2, en: "Say: I sent a message.",                       jp: "メッセージを おくりました。",   romaji: "messeeji o okurimashita." },
  { id: 213, level: 2, en: "Say: I wrote an email.",                       jp: "メールを かきました。",         romaji: "meeru o kakimashita." },
  { id: 9,   level: 2, en: "Say: I went to Tokyo yesterday.",              jp: "きのう とうきょうに いきました。", romaji: "kinou Toukyou ni ikimashita." },
  { id: 18,  level: 2, en: "Ask: What did you do yesterday?",              jp: "きのう なにを しましたか？",    romaji: "kinou nani o shimashita ka?" },
  { id: 214, level: 2, en: "Say: I don't drink coffee.",                   jp: "コーヒーを のみません。",       romaji: "koohii o nomimasen." },
  { id: 216, level: 2, en: "Say: I don't know that person.",               jp: "あの ひとを しりません。",      romaji: "ano hito o shirimasen." },
  { id: 217, level: 2, en: "Say: I don't have any money.",                 jp: "おかねが ありません。",         romaji: "okane ga arimasen." },
  { id: 10,  level: 2, en: "Say: I don't understand Japanese well.",       jp: "にほんごが よく わかりません。", romaji: "nihongo ga yoku wakarimasen." },
  { id: 14,  level: 2, en: "Ask: Do you have time now?",                   jp: "いま じかんが ありますか？",    romaji: "ima jikan ga arimasu ka?" },
  { id: 15,  level: 2, en: "Say: My wife is at home.",                     jp: "つまは うちに います。",        romaji: "tsuma wa uchi ni imasu.", hint: "います for people; あります for things" },
  { id: 220, level: 2, en: "Say: Nice weather today, huh?",                jp: "きょうは いい てんきですね。",   romaji: "kyou wa ii tenki desu ne.", hint: "~ね = right? / huh" },
  { id: 7,   level: 2, en: "Say: It's a little expensive.",                jp: "ちょっと たかいです。",         romaji: "chotto takai desu." },
  { id: 230, level: 2, en: "Say: It's not delicious.",                     jp: "おいしくないです。",            romaji: "oishikunai desu.",        hint: "i-adj negative: ~い → ~くない" },
  { id: 232, level: 2, en: "Say: It wasn't fun.",                          jp: "たのしくなかったです。",        romaji: "tanoshikunakatta desu.",  hint: "i-adj negative past" },
  { id: 233, level: 2, en: "Say: This book is interesting.",               jp: "この ほんは おもしろいです。",   romaji: "kono hon wa omoshiroi desu." },
  { id: 234, level: 2, en: "Say: My job is difficult.",                    jp: "しごとは むずかしいです。",     romaji: "shigoto wa muzukashii desu." },
  { id: 235, level: 2, en: "Say: This restaurant is famous.",              jp: "この レストランは ゆうめいです。", romaji: "kono resutoran wa yuumei desu." },
  { id: 221, level: 2, en: "Say: I have a meeting at three.",              jp: "さんじに かいぎが あります。",  romaji: "san-ji ni kaigi ga arimasu." },
  { id: 222, level: 2, en: "Say: I'll come at five.",                      jp: "ごじに きます。",               romaji: "go-ji ni kimasu." },
  { id: 223, level: 2, en: "Say: I'll call you later.",                    jp: "あとで でんわします。",         romaji: "ato de denwa shimasu." },
  { id: 21,  level: 2, en: "Say: I'll probably go tomorrow.",              jp: "あした たぶん いきます。",      romaji: "ashita tabun ikimasu." },
  { id: 224, level: 2, en: "Ask: Please give me water.",                   jp: "おみずを ください。",           romaji: "omizu o kudasai." },
  { id: 8,   level: 2, en: "Politely ask: Could you say it one more time?", jp: "もういちど いって ください。",  romaji: "mou ichido itte kudasai." },
  { id: 25,  level: 2, en: "Politely ask: Could you speak a little more slowly?", jp: "もうすこし ゆっくり はなして ください。", romaji: "mou sukoshi yukkuri hanashite kudasai." },
  { id: 225, level: 2, en: "Politely ask: Please take a photo.",           jp: "しゃしんを とって ください。",  romaji: "shashin o totte kudasai." },
  { id: 227, level: 2, en: "Politely ask: Please open the window.",        jp: "まどを あけて ください。",      romaji: "mado o akete kudasai." },
  { id: 229, level: 2, en: "Politely ask: Please show me.",                jp: "みせて ください。",             romaji: "misete kudasai." },
  { id: 239, level: 2, en: "Say: I forgot.",                               jp: "わすれました。",                romaji: "wasuremashita." },
  { id: 240, level: 2, en: "Say: I lost my wallet.",                       jp: "さいふを なくしました。",       romaji: "saifu o nakushimashita." },
  { id: 242, level: 2, en: "Say: I'm tired.",                              jp: "つかれました。",                romaji: "tsukaremashita.", hint: "literally 'I got tired' — used in present" },

  // ============================================================
  // Level 3 — Pimsleur 4-5 (~たい, ~ましょう, potential, adj past)
  // ============================================================
  { id: 2,   level: 3, en: "Say: I want to drink coffee.",                 jp: "コーヒーが のみたいです。",     romaji: "koohii ga nomitai desu.", hint: "verb-stem + たい = want to ___" },
  { id: 3,   level: 3, en: "Say: I would like to eat sushi.",              jp: "おすしが たべたいです。",       romaji: "osushi ga tabetai desu." },
  { id: 301, level: 3, en: "Say: I want to study Japanese.",               jp: "にほんごを べんきょうしたいです。", romaji: "nihongo o benkyou shitai desu." },
  { id: 302, level: 3, en: "Say: I want to sleep.",                        jp: "ねたいです。",                  romaji: "netai desu." },
  { id: 303, level: 3, en: "Say: I want to rest.",                         jp: "やすみたいです。",              romaji: "yasumitai desu." },
  { id: 305, level: 3, en: "Say: I want to learn more.",                   jp: "もっと まなびたいです。",       romaji: "motto manabitai desu." },
  { id: 307, level: 3, en: "Say: I want to live in Japan.",                jp: "にほんに すみたいです。",       romaji: "nihon ni sumitai desu." },
  { id: 12,  level: 3, en: "Say: I'd like to go to a Japanese restaurant tonight.", jp: "こんばん にほんりょうりの レストランに いきたいです。", romaji: "konban nihonryouri no resutoran ni ikitai desu." },
  { id: 23,  level: 3, en: "Ask: Where do you want to go?",                jp: "どこに いきたいですか？",       romaji: "doko ni ikitai desu ka?" },
  { id: 22,  level: 3, en: "Say: I don't want to drink alcohol today.",    jp: "きょうは おさけを のみたくないです。", romaji: "kyou wa osake o nomitaku nai desu.", hint: "~たい → ~たくない" },
  { id: 325, level: 3, en: "Say: I don't want to go.",                     jp: "いきたくないです。",            romaji: "ikitaku nai desu." },
  { id: 326, level: 3, en: "Say: I didn't want to wake up.",               jp: "おきたくなかったです。",        romaji: "okitaku nakatta desu." },
  { id: 327, level: 3, en: "Say: I want a new phone.",                     jp: "あたらしい でんわが ほしいです。", romaji: "atarashii denwa ga hoshii desu.", hint: "~が ほしい = want (a thing)" },
  { id: 328, level: 3, en: "Say: I don't need presents.",                  jp: "プレゼントは いりません。",     romaji: "purezento wa irimasen." },
  { id: 4,   level: 3, en: "Ask a friend: Shall we go together?",          jp: "いっしょに いきましょうか？",   romaji: "issho ni ikimashou ka?" },
  { id: 17,  level: 3, en: "Say: Let's meet at seven o'clock.",            jp: "しちじに あいましょう。",       romaji: "shichi-ji ni aimashou." },
  { id: 308, level: 3, en: "Say: Let's eat.",                              jp: "たべましょう。",                romaji: "tabemashou." },
  { id: 309, level: 3, en: "Say: Let's go home.",                          jp: "かえりましょう。",              romaji: "kaerimashou." },
  { id: 310, level: 3, en: "Say: Let's get started.",                      jp: "はじめましょう。",              romaji: "hajimemashou." },
  { id: 312, level: 3, en: "Say: Let's take a break.",                     jp: "やすみましょう。",              romaji: "yasumimashou." },
  { id: 313, level: 3, en: "Say: Let's talk in Japanese.",                 jp: "にほんごで はなしましょう。",   romaji: "nihongo de hanashimashou." },
  { id: 314, level: 3, en: "Offer help: Shall I help?",                    jp: "てつだいましょうか？",          romaji: "tetsudaimashou ka?" },
  { id: 315, level: 3, en: "Suggest: Shall we take a taxi?",               jp: "タクシーに のりましょうか？",   romaji: "takushii ni norimashou ka?" },
  { id: 20,  level: 3, en: "Ask a stranger: Excuse me, do you speak English?", jp: "すみません、えいごが はなせますか？", romaji: "sumimasen, eigo ga hanasemasu ka?", hint: "potential form" },
  { id: 316, level: 3, en: "Say: I can speak a little Japanese.",          jp: "にほんごが すこし はなせます。", romaji: "nihongo ga sukoshi hanasemasu." },
  { id: 317, level: 3, en: "Say: I can read hiragana.",                    jp: "ひらがなが よめます。",         romaji: "hiragana ga yomemasu." },
  { id: 318, level: 3, en: "Say: I can't read kanji yet.",                 jp: "かんじは まだ よめません。",    romaji: "kanji wa mada yomemasen." },
  { id: 319, level: 3, en: "Say: I can cook.",                             jp: "りょうりが できます。",         romaji: "ryouri ga dekimasu." },
  { id: 320, level: 3, en: "Ask: Can you swim?",                           jp: "およげますか？",                 romaji: "oyogemasu ka?" },
  { id: 19,  level: 3, en: "Say: It was very delicious.",                  jp: "とても おいしかったです。",     romaji: "totemo oishikatta desu.", hint: "i-adj past: ~い → ~かった" },
  { id: 321, level: 3, en: "Say: The movie was interesting.",              jp: "えいがは おもしろかったです。", romaji: "eiga wa omoshirokatta desu." },
  { id: 322, level: 3, en: "Say: The trip was fun.",                       jp: "りょこうは たのしかったです。", romaji: "ryokou wa tanoshikatta desu." },
  { id: 323, level: 3, en: "Say: I wasn't busy yesterday.",                jp: "きのうは いそがしくなかったです。", romaji: "kinou wa isogashikunakatta desu." },
  { id: 324, level: 3, en: "Say: She was kind.",                           jp: "かのじょは やさしかったです。", romaji: "kanojo wa yasashikatta desu." },
  { id: 24,  level: 3, en: "Say: My Japanese isn't very good yet.",        jp: "にほんごは まだ あまり じょうずじゃ ありません。", romaji: "nihongo wa mada amari jouzu ja arimasen.", hint: "あまり ~ない = not very" },
  { id: 329, level: 3, en: "Say: It's a little far.",                      jp: "ちょっと とおいです。",         romaji: "chotto tooi desu." },
  { id: 330, level: 3, en: "Say: It's very close.",                        jp: "とても ちかいです。",           romaji: "totemo chikai desu." },

  // ============================================================
  // Level 4 — Intermediate (~ている, ~たことがある, must/can, comparison)
  // ============================================================
  { id: 410, level: 4, en: "Say: I'm studying Japanese now.",              jp: "いま にほんごを べんきょうして います。", romaji: "ima nihongo o benkyou shite imasu.", hint: "~て います = -ing / ongoing" },
  { id: 411, level: 4, en: "Say: She's watching TV.",                      jp: "かのじょは テレビを みて います。", romaji: "kanojo wa terebi o mite imasu." },
  { id: 412, level: 4, en: "Say: He works at a bank.",                     jp: "かれは ぎんこうで はたらいて います。", romaji: "kare wa ginkou de hataraite imasu.", hint: "~ている also = habitually does" },
  { id: 413, level: 4, en: "Say: I live in Tokyo.",                        jp: "とうきょうに すんで います。",  romaji: "Toukyou ni sunde imasu." },
  { id: 414, level: 4, en: "Say: I know that person.",                     jp: "あの ひとを しって います。",   romaji: "ano hito o shitte imasu.", hint: "know = しっています (not しります)" },
  { id: 415, level: 4, en: "Say: I've eaten sushi before.",                jp: "おすしを たべた ことが あります。", romaji: "osushi o tabeta koto ga arimasu.", hint: "past plain + ことが あります = have done" },
  { id: 416, level: 4, en: "Say: I've never been to Kyoto.",               jp: "きょうとに いった ことが ありません。", romaji: "Kyouto ni itta koto ga arimasen." },
  { id: 417, level: 4, en: "Say: I've heard that song before.",            jp: "その うたを きいた ことが あります。", romaji: "sono uta o kiita koto ga arimasu." },
  { id: 13,  level: 4, en: "Say: I have to work tomorrow.",                jp: "あした はたらかなければ なりません。", romaji: "ashita hatarakanakereba narimasen.", hint: "~なければ なりません = must" },
  { id: 418, level: 4, en: "Say: I have to study tonight.",                jp: "こんばん べんきょうしなければ なりません。", romaji: "konban benkyou shinakereba narimasen." },
  { id: 419, level: 4, en: "Say: I have to wake up early tomorrow.",       jp: "あした はやく おきなければ なりません。", romaji: "ashita hayaku okinakereba narimasen." },
  { id: 420, level: 4, en: "Say: You don't have to apologize.",            jp: "あやまらなくても いいです。",   romaji: "ayamaranakute mo ii desu.", hint: "~なくても いい = don't have to" },
  { id: 421, level: 4, en: "Ask: May I sit here?",                         jp: "ここに すわっても いいですか？", romaji: "koko ni suwatte mo ii desu ka?", hint: "~ても いい = may ___" },
  { id: 422, level: 4, en: "Ask: May I use this?",                         jp: "これを つかっても いいですか？", romaji: "kore o tsukatte mo ii desu ka?" },
  { id: 423, level: 4, en: "Say: You must not smoke here.",                jp: "ここで たばこを すっては いけません。", romaji: "koko de tabako o sutte wa ikemasen.", hint: "~ては いけません = must not" },
  { id: 424, level: 4, en: "Say: I think this is correct.",                jp: "これは ただしいと おもいます。", romaji: "kore wa tadashii to omoimasu.", hint: "plain + と おもいます = I think" },
  { id: 425, level: 4, en: "Say: I think she's coming.",                   jp: "かのじょは くると おもいます。", romaji: "kanojo wa kuru to omoimasu." },
  { id: 426, level: 4, en: "Say: He said he was tired.",                   jp: "かれは つかれたと いいました。", romaji: "kare wa tsukareta to iimashita.", hint: "plain + と いいました = said" },
  { id: 427, level: 4, en: "Say: I'm better at English than Japanese.",    jp: "にほんごより えいごの ほうが じょうずです。", romaji: "nihongo yori eigo no hou ga jouzu desu.", hint: "より = than; ほう = side" },
  { id: 428, level: 4, en: "Say: Sushi is more delicious than ramen.",     jp: "ラーメンより おすしの ほうが おいしいです。", romaji: "raamen yori osushi no hou ga oishii desu." },
  { id: 429, level: 4, en: "Say: I'm good at cooking.",                    jp: "りょうりが じょうずです。",     romaji: "ryouri ga jouzu desu." },
  { id: 430, level: 4, en: "Say: I'm bad at math.",                        jp: "すうがくが にがてです。",       romaji: "suugaku ga nigate desu." },
  { id: 431, level: 4, en: "Say: I like reading books.",                   jp: "ほんを よむのが すきです。",    romaji: "hon o yomu no ga suki desu.", hint: "verb plain + の = the act of ___ing" },
  { id: 432, level: 4, en: "Say: I sometimes go to the gym.",              jp: "ときどき ジムに いきます。",    romaji: "tokidoki jimu ni ikimasu." },
  { id: 433, level: 4, en: "Say: I usually have coffee in the morning.",   jp: "たいてい あさ コーヒーを のみます。", romaji: "taitei asa koohii o nomimasu." },
  { id: 434, level: 4, en: "Say: I work while listening to music.",        jp: "おんがくを ききながら しごとを します。", romaji: "ongaku o kikinagara shigoto o shimasu.", hint: "~ながら = while ___ing" },

  // ============================================================
  // Level 5 — Conversational (because/if/when, embedded clauses)
  // ============================================================
  { id: 510, level: 5, en: "Say: I can't go because I'm busy.",            jp: "いそがしいから、いけません。",  romaji: "isogashii kara, ikemasen.", hint: "~から = because (reason first)" },
  { id: 501, level: 5, en: "Say: Because it was raining, I didn't go out.", jp: "あめが ふって いたから、でかけませんでした。", romaji: "ame ga futte ita kara, dekakemasen deshita." },
  { id: 511, level: 5, en: "Say: I went home because it got cold.",        jp: "さむく なったから、かえりました。", romaji: "samuku natta kara, kaerimashita.", hint: "なる = become" },
  { id: 502, level: 5, en: "Say: If you have time, let's get coffee.",     jp: "じかんが あれば、コーヒーを のみましょう。", romaji: "jikan ga areba, koohii o nomimashou.", hint: "~ば = if" },
  { id: 513, level: 5, en: "Say: If it's sunny tomorrow, let's go to the park.", jp: "あした はれたら、こうえんに いきましょう。", romaji: "ashita haretara, kouen ni ikimashou.", hint: "~たら = if/when" },
  { id: 512, level: 5, en: "Say: If you eat too much, you'll gain weight.", jp: "たべすぎると ふとりますよ。",  romaji: "tabesugiru to futorimasu yo.", hint: "~と = whenever/if (natural consequence)" },
  { id: 503, level: 5, en: "Say: When I was a child, I lived in Osaka.",   jp: "こどもの とき、おおさかに すんで いました。", romaji: "kodomo no toki, oosaka ni sunde imashita.", hint: "~の とき = when (was) ___" },
  { id: 514, level: 5, en: "Say: When I was a student, I studied a lot.",  jp: "がくせいの とき、よく べんきょうしました。", romaji: "gakusei no toki, yoku benkyou shimashita." },
  { id: 515, level: 5, en: "Say: Before going to bed, I brush my teeth.",  jp: "ねる まえに、はを みがきます。", romaji: "neru mae ni, ha o migakimasu.", hint: "plain + まえに = before ___ing" },
  { id: 516, level: 5, en: "Say: After eating, let's go for a walk.",      jp: "たべた あとで、さんぽしましょう。", romaji: "tabeta ato de, sanpo shimashou.", hint: "past plain + あとで = after ___ing" },
  { id: 505, level: 5, en: "Say: After I finish work, I'll go home.",      jp: "しごとが おわってから、うちに かえります。", romaji: "shigoto ga owatte kara, uchi ni kaerimasu.", hint: "~てから = after ___ing" },
  { id: 504, level: 5, en: "Say: Even if it's expensive, I want to buy it.", jp: "たかくても、かいたいです。",   romaji: "takakute mo, kaitai desu.", hint: "~ても = even if" },
  { id: 517, level: 5, en: "Say: Even if it rains, I'll go.",              jp: "あめが ふっても、いきます。",   romaji: "ame ga futte mo, ikimasu." },
  { id: 506, level: 5, en: "Say: I haven't decided what to do yet.",       jp: "なにを するか まだ きめて いません。", romaji: "nani o suru ka mada kimete imasen.", hint: "embedded question with か" },
  { id: 518, level: 5, en: "Say: I don't know what to do.",                jp: "なにを すれば いいか わかりません。", romaji: "nani o sureba ii ka wakarimasen." },
  { id: 519, level: 5, en: "Say: I forgot where I parked.",                jp: "どこに とめたか わすれました。", romaji: "doko ni tometa ka wasuremashita." },
  { id: 508, level: 5, en: "Say: The restaurant I went to yesterday was really good.", jp: "きのう いった レストランは とても よかったです。", romaji: "kinou itta resutoran wa totemo yokatta desu.", hint: "plain past modifies noun (relative clause)" },
  { id: 520, level: 5, en: "Say: The person I met yesterday was kind.",    jp: "きのう あった ひとは やさしかったです。", romaji: "kinou atta hito wa yasashikatta desu." },
  { id: 521, level: 5, en: "Say: The food my mom makes is the best.",      jp: "ははが つくる りょうりが いちばん おいしいです。", romaji: "haha ga tsukuru ryouri ga ichiban oishii desu." },
  { id: 524, level: 5, en: "Say: It looks delicious.",                     jp: "おいしそうです。",              romaji: "oishisou desu.", hint: "i-adj stem + そう = looks ___" },
  { id: 525, level: 5, en: "Say: It looks like it's going to rain.",       jp: "あめが ふりそうです。",         romaji: "ame ga furisou desu.", hint: "verb stem + そう = looks like ___" },
  { id: 526, level: 5, en: "Say: She seems busy.",                         jp: "かのじょは いそがしい みたいです。", romaji: "kanojo wa isogashii mitai desu.", hint: "~みたい = seems / looks like" },
  { id: 527, level: 5, en: "Say: It might rain tomorrow.",                 jp: "あした あめが ふるかも しれません。", romaji: "ashita ame ga furu kamo shiremasen.", hint: "~かもしれません = might" },
  { id: 528, level: 5, en: "Say: He might come.",                          jp: "かれは くるかも しれません。",  romaji: "kare wa kuru kamo shiremasen." },
  { id: 529, level: 5, en: "Say: I've come to understand Japanese.",       jp: "にほんごが わかるように なりました。", romaji: "nihongo ga wakaru you ni narimashita.", hint: "~ように なる = come to ___" },
  { id: 530, level: 5, en: "Say: I can read kanji now (didn't used to).",  jp: "かんじが よめるように なりました。", romaji: "kanji ga yomeru you ni narimashita." },
  { id: 532, level: 5, en: "Say: On weekends I read and watch movies (among other things).", jp: "しゅうまつは ほんを よんだり、えいがを みたり します。", romaji: "shuumatsu wa hon o yondari, eiga o mitari shimasu.", hint: "~たり ~たり する = do A and B (non-exhaustive)" },
  { id: 533, level: 5, en: "Say: It's gradually getting colder.",          jp: "だんだん さむく なって きました。", romaji: "dandan samuku natte kimashita.", hint: "~なってくる = becoming ___ over time" },
  { id: 534, level: 5, en: "Say: I'm thinking of going to Japan.",         jp: "にほんに いこうと おもって います。", romaji: "nihon ni ikou to omotte imasu.", hint: "volitional + と おもって います = thinking of ___ing" },
  { id: 522, level: 5, en: "Say casually: I'm gonna head out.",            jp: "もう いくよ。",                  romaji: "mou iku yo.", hint: "plain form + よ (casual)" },
  { id: 507, level: 5, en: "Say casually: I'm going to bed — I'm sleepy.", jp: "ねむいから もう ねるよ。",      romaji: "nemui kara mou neru yo." },
  { id: 531, level: 5, en: "Say (reporting): She said she'd come.",        jp: "かのじょは くるって いって いました。", romaji: "kanojo wa kuru tte itte imashita.", hint: "って = casual quote marker" },
];
