// Service worker — offline app shell for the Hanasou PWA.
// Bump CACHE when the precached shell list changes to evict the old cache.
const CACHE = "hanasou-v275";
const SHELL = [
  "./",
  "index.html",
  "styles.css",
  "theme.css",
  "ui-polish.css",
  "subway.css",
  "interactive-learning.css",
  "stampbook.js",
  "stampbook.css",
  "app.js",
  "theme.js",
  "ui-polish.js",
  "lessons.js",
  "kana.js",
  "emoji.js",
  "interactive-learning.js",
  "assets/sfx-chime.wav",
  "assets/kana/h-a.png",
  "assets/kana/h-ba.png",
  "assets/kana/h-be.png",
  "assets/kana/h-bi.png",
  "assets/kana/h-bo.png",
  "assets/kana/h-bu.png",
  "assets/kana/h-chi.png",
  "assets/kana/h-da.png",
  "assets/kana/h-de.png",
  "assets/kana/h-di.png",
  "assets/kana/h-do.png",
  "assets/kana/h-du.png",
  "assets/kana/h-e.png",
  "assets/kana/h-fu.png",
  "assets/kana/h-ga.png",
  "assets/kana/h-ge.png",
  "assets/kana/h-gi.png",
  "assets/kana/h-go.png",
  "assets/kana/h-gu.png",
  "assets/kana/h-ha.png",
  "assets/kana/h-he.png",
  "assets/kana/h-hi.png",
  "assets/kana/h-ho.png",
  "assets/kana/h-i.png",
  "assets/kana/h-ji.png",
  "assets/kana/h-ka.png",
  "assets/kana/h-ke.png",
  "assets/kana/h-ki.png",
  "assets/kana/h-ko.png",
  "assets/kana/h-ku.png",
  "assets/kana/h-ma.png",
  "assets/kana/h-me.png",
  "assets/kana/h-mi.png",
  "assets/kana/h-mo.png",
  "assets/kana/h-mu.png",
  "assets/kana/h-n.png",
  "assets/kana/h-na.png",
  "assets/kana/h-ne.png",
  "assets/kana/h-ni.png",
  "assets/kana/h-no.png",
  "assets/kana/h-nu.png",
  "assets/kana/h-o.png",
  "assets/kana/h-pa.png",
  "assets/kana/h-pe.png",
  "assets/kana/h-pi.png",
  "assets/kana/h-po.png",
  "assets/kana/h-pu.png",
  "assets/kana/h-ra.png",
  "assets/kana/h-re.png",
  "assets/kana/h-ri.png",
  "assets/kana/h-ro.png",
  "assets/kana/h-ru.png",
  "assets/kana/h-sa.png",
  "assets/kana/h-se.png",
  "assets/kana/h-shi.png",
  "assets/kana/h-so.png",
  "assets/kana/h-su.png",
  "assets/kana/h-ta.png",
  "assets/kana/h-te.png",
  "assets/kana/h-to.png",
  "assets/kana/h-tsu.png",
  "assets/kana/h-u.png",
  "assets/kana/h-wa.png",
  "assets/kana/h-wo.png",
  "assets/kana/h-ya.png",
  "assets/kana/h-yo.png",
  "assets/kana/h-yu.png",
  "assets/kana/h-za.png",
  "assets/kana/h-ze.png",
  "assets/kana/h-zo.png",
  "assets/kana/h-zu.png",
  "assets/kana/k-a.png",
  "assets/kana/k-ba.png",
  "assets/kana/k-be.png",
  "assets/kana/k-bi.png",
  "assets/kana/k-bo.png",
  "assets/kana/k-bu.png",
  "assets/kana/k-chi.png",
  "assets/kana/k-da.png",
  "assets/kana/k-de.png",
  "assets/kana/k-di.png",
  "assets/kana/k-do.png",
  "assets/kana/k-du.png",
  "assets/kana/k-e.png",
  "assets/kana/k-fu.png",
  "assets/kana/k-ga.png",
  "assets/kana/k-ge.png",
  "assets/kana/k-gi.png",
  "assets/kana/k-go.png",
  "assets/kana/k-gu.png",
  "assets/kana/k-ha.png",
  "assets/kana/k-he.png",
  "assets/kana/k-hi.png",
  "assets/kana/k-ho.png",
  "assets/kana/k-i.png",
  "assets/kana/k-ji.png",
  "assets/kana/k-ka.png",
  "assets/kana/k-ke.png",
  "assets/kana/k-ki.png",
  "assets/kana/k-ko.png",
  "assets/kana/k-ku.png",
  "assets/kana/k-ma.png",
  "assets/kana/k-me.png",
  "assets/kana/k-mi.png",
  "assets/kana/k-mo.png",
  "assets/kana/k-mu.png",
  "assets/kana/k-n.png",
  "assets/kana/k-na.png",
  "assets/kana/k-ne.png",
  "assets/kana/k-ni.png",
  "assets/kana/k-no.png",
  "assets/kana/k-nu.png",
  "assets/kana/k-o.png",
  "assets/kana/k-pa.png",
  "assets/kana/k-pe.png",
  "assets/kana/k-pi.png",
  "assets/kana/k-po.png",
  "assets/kana/k-pu.png",
  "assets/kana/k-ra.png",
  "assets/kana/k-re.png",
  "assets/kana/k-ri.png",
  "assets/kana/k-ro.png",
  "assets/kana/k-ru.png",
  "assets/kana/k-sa.png",
  "assets/kana/k-se.png",
  "assets/kana/k-shi.png",
  "assets/kana/k-so.png",
  "assets/kana/k-su.png",
  "assets/kana/k-ta.png",
  "assets/kana/k-te.png",
  "assets/kana/k-to.png",
  "assets/kana/k-tsu.png",
  "assets/kana/k-u.png",
  "assets/kana/k-wa.png",
  "assets/kana/k-wo.png",
  "assets/kana/k-ya.png",
  "assets/kana/k-yo.png",
  "assets/kana/k-yu.png",
  "assets/kana/k-za.png",
  "assets/kana/k-ze.png",
  "assets/kana/k-zo.png",
  "assets/kana/k-zu.png",
  "assets/story/people/aki-kid.png",
  "assets/story/people/aki-teen.png",
  "assets/story/people/aki-adult.png",
  "assets/story/people/aki-old.png",
  "assets/story/people/beni-kid.png",
  "assets/story/people/beni-teen.png",
  "assets/story/people/beni-adult.png",
  "assets/story/people/beni-old.png",
  "assets/story/people/kai-kid.png",
  "assets/story/people/kai-teen.png",
  "assets/story/people/kai-adult.png",
  "assets/story/people/kai-old.png",
  "assets/story/people/yuki-kid.png",
  "assets/story/people/yuki-teen.png",
  "assets/story/people/yuki-adult.png",
  "assets/story/people/yuki-old.png",
  "assets/story/sushi.png",
  "assets/story/peach.png",
  "assets/story/persimmon.png",
  "assets/story/cup.png",
  "assets/story/water.png",
  "assets/story/coffee.png",
  "assets/story/menu.png",
  "assets/story/dogface.png",
  "assets/story/whitecat.png",
  "assets/story/cat.png",
  "assets/story/cow.png",
  "assets/story/octopus.png",
  "assets/story/bird.png",
  "assets/story/book-window.png",
  "assets/story/book-stripes.png",
  "assets/story/book-circle.png",
  "assets/story/bag.png",
  "assets/story/telephone.png",
  "assets/story/umbrella.png",
  "assets/story/ticket.png",
  "assets/story/chair.png",
  "assets/story/house.png",
  "assets/story/station.png",
  "assets/story/town.png",
  "assets/story/schooldesk.png",
  "assets/story/wc.png",
  "assets/story/signal.png",
  "assets/story/car.png",
  "assets/story/train.png",
  "assets/story/bus.png",
  "assets/story/boat.png",
  "assets/story/sea.png",
  "assets/story/winter.png",
  "assets/story/sakura.png",
  "assets/story/flower.png",
  "assets/story/redflower.png",
  "assets/story/mountain.png",
  "assets/story/sun.png",
  "assets/story/moon.png",
  "assets/story/star.png",
  "assets/story/japanmap.png",
  "assets/story/usflag.png",
  "assets/story/mystery.png",
  "assets/story/clockface.png",
  "assets/story/bigface.png",
  "assets/story/redface.png",
  "assets/story/coin100.png",
  "assets/story/hand.png",
  "assets/story/basket.png",
  "assets/story/mochiko-cheer.png",
  "assets/story/mochiko-think.png",
  "assets/story/mochiko-cry.png",
  "assets/story/mochiko-thumbs.png",
  "assets/story/bg-room.jpg",
  "assets/story/bg-street.jpg",
  "assets/story/bg-shop.jpg",
  "assets/story/bg-onsen.jpg",
  "assets/story/bg-aquarium.jpg",
  "assets/story/beer.png",
  "assets/story/redwine.png",
  "assets/story/whitewine.png",
  "assets/story/greentea.png",
  "assets/story/icedtea.png",
  "assets/story/cola.png",
  "assets/story/sake.png",
  "assets/story/sukiyaki.png",
  "assets/story/breakfast.png",
  "assets/story/yakitori.png",
  "assets/story/curry.png",
  "assets/story/cake.png",
  "assets/story/wagashi.png",
  "assets/story/karaage.png",
  "assets/story/grilledfish.png",
  "assets/story/gloves.png",
  "assets/story/shoes.png",
  "assets/story/wallet.png",
  "assets/story/medicine.png",
  "assets/story/map.png",
  "assets/story/card.png",
  "assets/story/tv.png",
  "assets/story/gohan.png",
  "assets/story/natto.png",
  "assets/story/emptyplate.png",
  "assets/story/toothbrush.png",
  "assets/story/alarmclock.png",
  "assets/story/raincloud.png",
  "assets/story/chatbubble.png",
  "assets/story/suitcase.png",
  "assets/story/thief.png",
  "assets/story/bill.png",
  "assets/story/cinema.png",
  "assets/story/park.png",
  "assets/story/office.png",
  "assets/story/school.png",
  "assets/story/airport.png",
  "assets/story/hospital.png",
  "assets/story/bicycle.png",
  "assets/story/taxi.png",
  "assets/story/subway.png",
  "assets/story/bridge.png",
  "assets/story/crossing.png",
  "assets/story/platform.png",
  "assets/story/bed.png",
  "assets/story/bathtub.png",
  "assets/story/window.png",
  "assets/story/smartphone.png",
  "assets/story/meat.png",
  "assets/story/bread.png",
  "assets/story/vegetables.png",
  "assets/story/onigiri.png",
  "assets/story/cigarette.png",
  "assets/story/headphones.png",
  "assets/story/camera.png",
  "assets/story/people/kai-adult-drink.png",
  "assets/story/people/kai-adult-eat.png",
  "assets/story/people/kai-adult-read.png",
  "assets/story/people/kai-adult-wake.png",
  "assets/story/people/kai-adult-walk.png",
  "assets/story/people/kai-adult-study.png",
  "assets/story/people/aki-adult-drink.png",
  "assets/story/people/aki-adult-eat.png",
  "assets/story/people/aki-adult-read.png",
  "assets/story/people/aki-adult-wake.png",
  "assets/story/people/aki-adult-walk.png",
  "assets/story/people/aki-adult-study.png",
  "assets/story/people/beni-adult-drink.png",
  "assets/story/people/beni-adult-eat.png",
  "assets/story/people/beni-adult-read.png",
  "assets/story/people/beni-adult-wake.png",
  "assets/story/people/beni-adult-walk.png",
  "assets/story/people/beni-adult-study.png",
  "assets/story/people/yuki-adult-drink.png",
  "assets/story/people/yuki-adult-eat.png",
  "assets/story/people/yuki-adult-read.png",
  "assets/story/people/yuki-adult-wake.png",
  "assets/story/people/yuki-adult-walk.png",
  "assets/story/people/yuki-adult-study.png",
  "assets/story/shelf.png",
  "assets/story/table.png",
  "assets/covers/activities.png",
  "assets/covers/adj-negative.png",
  "assets/covers/adj-noun.png",
  "assets/covers/adjectives.png",
  "assets/covers/age.png",
  "assets/covers/because.png",
  "assets/covers/business-keigo.png",
  "assets/covers/but-kedo.png",
  "assets/covers/cafe.png",
  "assets/covers/can-do.png",
  "assets/covers/causative-passive.png",
  "assets/covers/causative.png",
  "assets/covers/coming-going.png",
  "assets/covers/comparing.png",
  "assets/covers/conditionals.png",
  "assets/covers/counters.png",
  "assets/covers/directions.png",
  "assets/covers/does-this-go.png",
  "assets/covers/even-though.png",
  "assets/covers/experience.png",
  "assets/covers/favors.png",
  "assets/covers/frequency.png",
  "assets/covers/greetings.png",
  "assets/covers/had-better.png",
  "assets/covers/have-to.png",
  "assets/covers/how-far.png",
  "assets/covers/i-think.png",
  "assets/covers/intend.png",
  "assets/covers/intro.png",
  "assets/covers/kagiri.png",
  "assets/covers/kenjougo.png",
  "assets/covers/l0-a.png",
  "assets/covers/l0-dakuten.png",
  "assets/covers/l0-ha.png",
  "assets/covers/l0-ka.png",
  "assets/covers/l0-ma.png",
  "assets/covers/l0-na.png",
  "assets/covers/l0-ra.png",
  "assets/covers/l0-sa.png",
  "assets/covers/l0-ta.png",
  "assets/covers/l0-wa.png",
  "assets/covers/l0-ya.png",
  "assets/covers/lets.png",
  "assets/covers/likes.png",
  "assets/covers/making-plans.png",
  "assets/covers/money.png",
  "assets/covers/monono.png",
  "assets/covers/na-adj.png",
  "assets/covers/negative.png",
  "assets/covers/ni-oite.png",
  "assets/covers/numbers.png",
  "assets/covers/object.png",
  "assets/covers/passive.png",
  "assets/covers/past-1.png",
  "assets/covers/past-negative.png",
  "assets/covers/permission.png",
  "assets/covers/plain-form.png",
  "assets/covers/potential.png",
  "assets/covers/quoting.png",
  "assets/covers/reactions.png",
  "assets/covers/routine.png",
  "assets/covers/seems.png",
  "assets/covers/sequence-te.png",
  "assets/covers/sequence.png",
  "assets/covers/shop.png",
  "assets/covers/should-supposed.png",
  "assets/covers/sonkeigo.png",
  "assets/covers/te-form.png",
  "assets/covers/te-iru.png",
  "assets/covers/te-please.png",
  "assets/covers/telling-time.png",
  "assets/covers/this-that.png",
  "assets/covers/tickets.png",
  "assets/covers/timing.png",
  "assets/covers/transport.png",
  "assets/covers/travel-trouble.png",
  "assets/covers/try-doing.png",
  "assets/covers/verbs.png",
  "assets/covers/wake.png",
  "assets/covers/wants.png",
  "assets/covers/was-were.png",
  "assets/covers/where.png",
  "assets/covers/you-ni.png",
  "assets/covers/zaru-o-enai.png",
  "prompts.js",
  "manifest.webmanifest",
  "audio/manifest.json",
  "icon-192.png",
  "icon-512.png",
  "icon-maskable-512.png",
  "apple-touch-icon-180.png",
];

// Precache every pre-generated audio clip the manifest lists, so the app can
// speak offline right after install (best-effort — missing clips fall back to
// speechSynthesis, and the stale-while-revalidate handler caches the rest).
async function precacheAudio(cache) {
  try {
    const res = await fetch("audio/manifest.json", { cache: "no-cache" });
    if (!res.ok) return;
    const { clips, roleClips } = await res.json();
    const files = [];
    const walk = (map) => {
      for (const k in map || {}) {
        if (map[k].n) files.push("audio/" + map[k].n);
        if (map[k].s) files.push("audio/" + map[k].s);
      }
    };
    walk(clips);
    for (const role in roleClips || {}) walk(roleClips[role]);
    await Promise.all(files.map((f) =>
      fetch(f).then((r) => r.ok && cache.put(f, r.clone())).catch(() => {})
    ));
  } catch {}
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(SHELL).then(() => precacheAudio(c)))
  );
});

// The page asks us to activate immediately when the user taps "Reload".
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;                       // let API writes hit the network
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // ignore third-party requests
  if (url.pathname.startsWith("/api/")) return;           // never cache the sync API

  // Audio manifest: network-first so freshly generated clips are discovered
  // without a version bump. The clip files themselves are content-hashed
  // (so never stale) and keep using stale-while-revalidate below.
  if (url.pathname.endsWith("/audio/manifest.json")) {
    event.respondWith(
      fetch(req)
        .then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); return res; })
        .catch(() => caches.match(req))
    );
    return;
  }

  // Navigations: network-first so a fresh deploy is picked up, cache as offline
  // fallback. cache:"no-cache" bypasses the HTTP cache (Pages serves index with
  // max-age=600, which made reopen-right-after-a-deploy show the stale page).
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req, { cache: "no-cache" })
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put("index.html", copy));
          return res;
        })
        .catch(() => caches.match("index.html").then((r) => r || caches.match("./")))
    );
    return;
  }

  // Static assets: stale-while-revalidate — instant from cache, refresh in background.
  event.respondWith(
    caches.match(req).then((cached) => {
      const network = fetch(req)
        .then((res) => {
          if (res && res.ok && res.type === "basic") {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => cached);
      return cached || network;
    })
  );
});
